Repository elastic/ecs, pull requests merged in 2018-11, with the labels that each got.

#109 Rename url.href to url.original
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/url.yml
  template.json
Labels: discuss, ga-1.0, review

#157 Tweak note about 'IDs' being keyword to also mention 'codes'
  README.md
  docs/implementing.md
Labels: review

#171 Temporarily remove the `http` object...
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  template.json
  use-cases/filebeat-apache-access.md
  use-cases/web-logs.md
  use-cases/web-logs.yml
Labels: Beta1

#172 Temporarily remove the `user_agent` field set...
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/user_agent.yml
  template.json
  use-cases/filebeat-apache-access.md
  use-cases/web-logs.md
  use-cases/web-logs.yml
Labels: Beta1

#175 Remove src/dst.hostname, rename url.hostname to url.domain.
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/destination.yml
  schemas/source.yml
  schemas/url.yml
  template.json
Labels: Beta1

#173 Make Markdown links relative, so browsing a git ref stays in the same git ref
  README.md
  docs/about.md
  scripts/use-cases.py
  use-cases/apm.md
  use-cases/auditbeat.md
  use-cases/beats.md
  use-cases/filebeat-apache-access.md
  use-cases/kubernetes.md
  use-cases/logging.md
  use-cases/metricbeat.md
  use-cases/tls.md
  use-cases/web-logs.md
Labels: 1.0.0-beta1, documentation

#176 Update ecs.version and link warning to first release.
  CHANGELOG.md
  README.md
  docs/intro.md
  fields.yml
  schema.csv
  schemas/ecs.yml
Labels: review

#187 Add host.name field
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/host.yml
  template.json
  use-cases/kubernetes.md
Labels: review

#190 Add apache 2 license to ECS
  LICENSE.txt
  NOTICE.txt
Labels: review
