Repository elastic/ecs, pull requests merged in 2018-12, with the labels that each got.

#200 Add field process.thread.id
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/process.yml
  template.json
Labels: 1.0.0-beta2

#206 Introduce the `related.` field set with only one field, to start.
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/related.yml
  template.json
Labels: 1.0.0-beta2

#204 Add user.groups
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/user.yml
  template.json
Labels: 1.0.0-beta2

#203 Add minimal field set to represent groups.
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/group.yml
  template.json
Labels: 1.0.0-beta2

#211 Fix a 'typo' in the definition of `source`...
  CHANGELOG.md
  README.md
  fields.yml
  schemas/source.yml
Labels: 1.0.0-beta2

#207 Introduce url.full
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/url.yml
  template.json
Labels: 1.0.0-beta2

#209 Introduce process.executable.
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/process.yml
  template.json
Labels: 1.0.0-beta2

#215 Add `process.working_directory` and `process.start`.
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/process.yml
  template.json
Labels: 1.0.0-beta2

#196 Update file definition
  CHANGELOG.md
  README.md
  fields.yml
  schemas/file.yml
Labels: 1.0.0-beta2, documentation

#194 Clarify event definition - add metrics
  CHANGELOG.md
  README.md
  fields.yml
  schemas/event.yml
Labels: 1.0.0-beta2, documentation

#197 Clarify network definition
  CHANGELOG.md
  README.md
  fields.yml
  schemas/network.yml
Labels: 1.0.0-beta2, documentation

#195 Clarify host definition
  CHANGELOG.md
  README.md
  fields.yml
  schemas/host.yml
Labels: 1.0.0-beta2, documentation

#237 Re-introduce `http` precisely as it was, as of #d8cece6
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/http.yml
  template.json
  use-cases/filebeat-apache-access.md
  use-cases/web-logs.md
Labels: 1.0.0-beta2

#201 Add user.full_name
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/user.yml
  template.json
Labels: 1.0.0-beta2

#208 Introduce network.community_id
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/network.yml
  template.json
Labels: 1.0.0-beta2

#212 Clarify the semantics of `network.direction`
  CHANGELOG.md
  README.md
  fields.yml
  schemas/network.yml
Labels: 1.0.0-beta2

#179 Proposal for more straightforward network metrics fields.
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/destination.yml
  schemas/network.yml
  schemas/source.yml
  template.json
Labels: 1.0.0-beta2

#242 Event categorisation fields
  .gitignore
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/event.yml
  template.json
Labels: 1.0.0-beta2

#236 Add Top Level Client and Server Objects
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/client.yml
  schemas/geo.yml
  schemas/related.yml
  schemas/server.yml
  schemas/user.yml
  template.json
Labels: 1.0.0-beta2

#244 State that source and destination are also a pair.
  README.md
  fields.yml
  schemas/destination.yml
  schemas/source.yml
Labels: 1.0.0-beta2

#248 Add `geo.name` as the field for ad hoc location names.
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/geo.yml
  template.json
Labels: 1.0.0-beta2

#255 Fix url.original example
  README.md
  fields.yml
  schema.csv
  schemas/url.yml
Labels: 1.0.0-beta2, review

#258 Add `event.timezone`.
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/event.yml
  template.json
Labels: 1.0.0-beta2

#257 Add a new readme section for reserved top level field sets
  CHANGELOG.md
  README.md
  docs/implementing.md
Labels: 1.0.0-beta2

#262 Index `user_agent.original`, after all.
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/user_agent.yml
  template.json
  use-cases/filebeat-apache-access.md
  use-cases/web-logs.md
Labels: 1.0.0-beta2

#253 Protocol names and http method shall be lowercased
  CHANGELOG.md
  README.md
  docs/implementing.md
  fields.yml
  schema.csv
  schemas/http.yml
  schemas/network.yml
Labels: 1.0.0-beta2

#247 Introduce `source.address` and `destination.address`.
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/client.yml
  schemas/destination.yml
  schemas/server.yml
  schemas/source.yml
  template.json
Labels: 1.0.0-beta2

#239 Introduce size metrics for HTTP.
  CHANGELOG.md
  README.md
  fields.yml
  schema.csv
  schemas/http.yml
  template.json
  use-cases/web-logs.md
  use-cases/web-logs.yml
Labels: discuss

#271 Prepare 1.0.0-beta2 release
  CHANGELOG.md
  README.md
  docs/intro.md
  fields.yml
  schema.csv
  schemas/ecs.yml
Labels: review

#273 Remove the obsolete TODO file :-)
  TODO.md
Labels: needs backport

#266 Convert ECS doc from MD to asciidoc guide: initial setup
  docs/contributing.asciidoc
  docs/conventions.asciidoc
  docs/fields-gen.asciidoc
  docs/fields.asciidoc
  docs/glossary.asciidoc
  docs/guidelines.asciidoc
  docs/index.asciidoc
  docs/use-cases.asciidoc
Labels: documentation

#275 Add automation around docs generation
  .gitignore
  .travis.yml
  Makefile
Labels: review

#279 Add VERSION variable to Makefile
  Makefile
  scripts/template.go
  template.json
Labels: review

#282 Update template.json
  template.json
Labels: review

#287 Version Go deps and use Python virtualenv
  Makefile
  scripts/cmd/template/template.go
  scripts/go.mod
  scripts/go.sum
  scripts/requirements.txt
Labels: review

#249 Add code generator for Go
  CHANGELOG.md
  Makefile
  code/README.md
  code/go/ecs/README.md
  code/go/ecs/agent.go
  code/go/ecs/base.go
  code/go/ecs/client.go
  code/go/ecs/cloud.go
  code/go/ecs/container.go
  code/go/ecs/destination.go
  code/go/ecs/doc.go
  code/go/ecs/ecs.go
  code/go/ecs/error.go
  code/go/ecs/event.go
  code/go/ecs/file.go
  code/go/ecs/geo.go
  code/go/ecs/group.go
  code/go/ecs/host.go
  code/go/ecs/http.go
  code/go/ecs/log.go
  code/go/ecs/network.go
  code/go/ecs/observer.go
  code/go/ecs/organization.go
  code/go/ecs/os.go
  code/go/ecs/process.go
  code/go/ecs/related.go
  code/go/ecs/server.go
  code/go/ecs/service.go
  code/go/ecs/source.go
  code/go/ecs/url.go
  code/go/ecs/user.go
  code/go/ecs/user_agent.go
  code/go/ecs/version.go
  scripts/cmd/gocodegen/gocodegen.go
  scripts/go.mod
  scripts/go.sum
Labels: discuss
