Repository elastic/ecs, pull requests merged in 2018-09, with the labels that each got.

#108 Add Beats compatible fields.yml for ECS
  Makefile
  README.md
  fields.yml
  schemas/agent.yml
  schemas/base.yml
  schemas/cloud.yml
  schemas/container.yml
  schemas/destination.yml
  schemas/device.yml
  schemas/error.yml
  schemas/event.yml
  schemas/file.yml
  schemas/geo.yml
  schemas/host.yml
  schemas/http.yml
  schemas/kubernetes.yml
  schemas/log.yml
  schemas/network.yml
  schemas/organization.yml
  schemas/os.yml
  schemas/process.yml
  schemas/service.yml
  schemas/source.yml
  schemas/tls.yml
  schemas/url.yml
  schemas/user.yml
  schemas/user_agent.yml
  scripts/fields_header.yml
Labels: review

#116 Fix example when processed as asciidoc
  README.md
  fields.yml
  schema.csv
  schemas/base.yml
Labels: discuss

#118 Rename all nested fields mentioned in #103 to .keyword
  CHANGELOG.md
  README.md
  fields.yml
  schemas/file.yml
  schemas/network.yml
  schemas/url.yml
  template.json
Labels: ga-1.0
