Repository elastic/ecs, pull requests merged in 2019-11, with the labels that each got.

#606 Add TLS schema to ECS
  CHANGELOG.next.md
  code/go/ecs/tls.go
  docs/field-details.asciidoc
  docs/fields.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/legacy/template.json
  schema.json
  schemas/tls.yml
  scripts/go.mod
  use-cases/tls.md
Labels: enhancement, in progress

#581 Created the Vulnerability Schema
  CHANGELOG.next.md
  code/go/ecs/vulnerability.go
  docs/field-details.asciidoc
  docs/fields.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/legacy/template.json
  schema.json
  schemas/vulnerability.yml
Labels: enhancement

#615 Added `process.args_count`
  CHANGELOG.next.md
  code/go/ecs/process.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/legacy/template.json
  schema.json
  schemas/process.yml
Labels: 1.3.0, needs_backport

#625 Set the correct version in the 1.3 branch
  code/go/ecs/version.go
  docs/fields.asciidoc
  docs/index.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/legacy/template.json
  version
Labels: 1.3.0

#633 Split changelog in two sections
  CHANGELOG.next.md
Labels: 1.3.0, needs_backport

#621 Flesh out the csv a little
  CHANGELOG.next.md
  generated/csv/fields.csv
  scripts/generators/csv_generator.py
Labels: 1.1.0, 1.2.0, 1.3.0, needs_backport, v1.0.2

#635 Backport #615 to 1.3: Added `process.args_count`
  CHANGELOG.next.md
  code/go/ecs/process.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/legacy/template.json
  schema.json
  schemas/process.yml
Labels: backport

#634 Backport #633 to 1.3: Split changelog in two sections
  CHANGELOG.next.md
Labels: backport

#637 Backport #622 to 1.3: Adds links to the list of products that support ECS
  docs/index.asciidoc
  docs/products-solutions.asciidoc
Labels: backport

#638 Make the 'Index' column lowercase.
  generated/csv/fields.csv
  scripts/generators/csv_generator.py
Labels: 1.3.0, needs_backport

#631 Run misspell on the schema definitions too
  Makefile
  schemas/process.yml
Labels: 1.2.0, 1.3.0, needs_backport

#636 Remove TLS use case.
  use-cases/tls.md
  use-cases/tls.yml
Labels: 1.3.0, needs_backport

#640 Backport #621 to 1.3: Flesh out the csv a little
  CHANGELOG.next.md
  generated/csv/fields.csv
  scripts/generators/csv_generator.py
Labels: backport

#642 Backport #631 to 1.3: Run misspell on the schema definitions
  Makefile
  schemas/process.yml
Labels: backport

#627 Remove schema.json and the code that generates it
  CHANGELOG.next.md
  Makefile
  schema.json
  scripts/schemas.py
Labels: 1.3.0, cleanup, needs_backport

#643 Backport #627 to 1.3: Remove schema.json and the code that generates it
  CHANGELOG.next.md
  Makefile
  schema.json
  scripts/schemas.py
Labels: backport

#629 Remove the legacy Elasticsearch template
  CHANGELOG.next.md
  Makefile
  generated/legacy/template.json
Labels: 1.3.0, cleanup, needs_backport

#644 Backport #629 to 1.3: Remove the *legacy* Elasticsearch template
  CHANGELOG.next.md
  Makefile
  generated/legacy/template.json
Labels: backport

#646 Backport #614 to 1.3: Slight clarification of the wording for package.reference
  code/go/ecs/package.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/package.yml
Labels: 1.3.0, backport

#648 Cut the 1.3.0 changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: 1.3.0

#649 After the 1.3 release, version in master becomes 1.4.0-dev
  code/go/ecs/version.go
  docs/fields.asciidoc
  docs/index.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  version
Labels: 1.3.0

#654 Forward port the 1.3.0 changelog to master
  CHANGELOG.md
  CHANGELOG.next.md
Labels: 1.3.0
