Repository elastic/ecs, pull requests merged in 2019-04, with the labels that each got.

#430 Docs: Fix a table start to align with the stop
  docs/fields.asciidoc
  scripts/generators/asciidoc_fields.py
Labels: 1.0.0-docs, documentation

#425 Specify static output format for event.duration
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
  scripts/generators/beats.py
Labels: needs_backport, v1.0.1

#432 Backport #425 to 1.0: Specify static output format for event.duration
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
  scripts/generators/beats.py
Labels: backport, v1.0.1

#434 Backport #430 to 1.0: Docs: Fix a table start to align with the stop (#430)
  docs/fields.asciidoc
  scripts/generators/asciidoc_fields.py
Labels: backport, v1.0.1

#435 Adjust make targets to use docker/asciidoctor.
  Makefile
Labels: needs_backport, v1.0.1

#437 Backport #435 to 1.0: Adjust make targets for documentation to use docker/asciidoctor
  Makefile
Labels: backport, v1.0.1
