Repository elastic/ecs, pull requests merged in 2019-07, with the labels that each got.

#341 Add Autonomous System (AS) fields
  CHANGELOG.next.md
  code/go/ecs/as.go
  docs/field-details.asciidoc
  docs/fields.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/legacy/template.json
  schemas/as.yml
  scripts/cmd/gocodegen/gocodegen.go
Labels: review

#496 Update schema.json on 'make'
  Makefile
  schema.json
Labels: review

#502 Clarify `service.id` description.
  code/go/ecs/service.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schema.json
  schemas/service.yml
Labels: needs_backport, v1.0.2

#503 Backport #502 to 1.0: Clarify `service.id` description.
  code/go/ecs/service.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/service.yml
Labels: backport, v1.0.2
