Repository elastic/ecs, pull requests merged in 2019-12, with the labels that each got.

#657 Backport #655 to 1.2: Fix typo in DNS fields documentation
  code/go/ecs/dns.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schema.json
  schemas/dns.yml
Labels: backport

#660 [ECS] [Docs] Quick fix for table formatting
  code/go/ecs/vulnerability.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/vulnerability.yml
Labels: 1.3, bug, documentation, needs_backport

#656 Backport #655 to 1.3: Fix typo in DNS fields documentation
  code/go/ecs/dns.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/dns.yml
Labels: backport

#658 Backport #655 to 1.1: Fix typo in DNS fields documentation
  code/go/ecs/dns.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schema.json
  schemas/dns.yml
Labels: backport

#662 Remove tls.server.supported_ciphers field
  CHANGELOG.next.md
  code/go/ecs/tls.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/tls.yml
Labels: review

#664 Backport #660 to 1.3: Format URLs in vulnerability, to fix table formatting
  code/go/ecs/vulnerability.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/vulnerability.yml
Labels: 1.3, backport

#667 Remove tls.server.supported_ciphers field (#662)
  CHANGELOG.next.md
  code/go/ecs/tls.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/tls.yml
Labels: 1.3, backport

#668 Update version to 1.3.1
  code/go/ecs/version.go
  docs/fields.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  version
Labels: 1.3.1

#669 Cut the 1.3.1 changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: 1.3.1

#670 Forward port the 1.3.1 changelog to master (#669)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: 1.3.1

#684 Introducing doc section for the expected values in reserved fields
  code/go/ecs/event.go
  docs/field-details.asciidoc
  docs/field-values.asciidoc
  docs/index.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/README.md
  schemas/event.yml
  scripts/generator.py
  scripts/generators/asciidoc_fields.py
  scripts/generators/ecs_helpers.py
  scripts/schema_reader.py
  scripts/tests/test_ecs_helpers.py
  scripts/tests/test_schema_reader.py
Labels: categorization

#695 Set version to 1.4 in the release branch
  code/go/ecs/version.go
  docs/fields.asciidoc
  docs/index.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  version
Labels: 1.4.0

#692 Introduce the initial values for ECS categorization
  CHANGELOG.next.md
  code/go/ecs/event.go
  docs/field-details.asciidoc
  docs/field-values.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
  scripts/generators/asciidoc_fields.py
Labels: 1.4.0, categorization, needs_backport

#687 Workaround for Beats issue with default_field growing too big
  CHANGELOG.next.md
  code/go/ecs/host.go
  code/go/ecs/rule.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/host.yml
  schemas/rule.yml
  scripts/generators/beats.py
  scripts/generators/beats_default_fields_whitelist.yml
  scripts/generators/ecs_helpers.py
Labels: discuss, review
