Repository elastic/ecs, pull requests merged in 2019-05, with the labels that each got.

#311 Add process.pgid field for processes group id
  code/go/ecs/process.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/legacy/template.json
  schema.json
  schemas/process.yml
  scripts/cmd/gocodegen/gocodegen.go
Labels: enhancement, review

#454 Format port numbers and numeric IDs as strings
  CHANGELOG.next.md
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/client.yml
  schemas/destination.yml
  schemas/event.yml
  schemas/http.yml
  schemas/process.yml
  schemas/server.yml
  schemas/source.yml
  schemas/url.yml
Labels: review

#426 Add hash.* field set
  CHANGELOG.next.md
  Makefile
  code/go/ecs/hash.go
  docs/field-details.asciidoc
  docs/fields.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/legacy/template.json
  schemas/hash.yml
  use-cases/auditbeat.md
Labels: review

#470 Fix/add examples for the pid fields
  code/go/ecs/process.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/process.yml
Labels: needs_backport, v1.0.2

#466 Cut changelog for ECS 1.0.1...
  CHANGELOG.md
  CHANGELOG.next.md
Labels: v1.0.1

#467 Backport #454 to 1.0: Format port numbers and numeric IDs as strings
  CHANGELOG.next.md
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/client.yml
  schemas/destination.yml
  schemas/event.yml
  schemas/http.yml
  schemas/process.yml
  schemas/server.yml
  schemas/source.yml
  schemas/url.yml
Labels: backport, v1.0.2

#468 Backport #464 to 1.0: Fix exmple typo in process.yml
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/process.yml
Labels: backport, v1.0.2

#471 Backport #470 to 1.0: Fix/add examples for the pid fields
  code/go/ecs/process.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/process.yml
Labels: backport, v1.0.1

#472 Finalize 1.0.1 changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: v1.0.1
