Repository elastic/ecs, pull requests merged in 2019-02, with the labels that each got.

#319 Minor tweaks to contributor guidelines
  CONTRIBUTING.md
Labels: needs backport

#325 clarify host definition wording
  CHANGELOG.md
  README.md
  code/go/ecs/host.go
  fields.yml
  schema.json
  schemas/host.yml
Labels: 1.0.0-ga, needs backport, review

#331 Specify the `object_type` for field `labels`.
  CHANGELOG.md
  fields.yml
  schemas/base.yml
Labels: 1.0.0-ga, needs backport

#330 Introduction of an optional short field description
  CHANGELOG.md
  README.md
  code/go/ecs/agent.go
  code/go/ecs/base.go
  code/go/ecs/client.go
  code/go/ecs/cloud.go
  code/go/ecs/container.go
  code/go/ecs/ecs.go
  code/go/ecs/error.go
  code/go/ecs/event.go
  code/go/ecs/file.go
  code/go/ecs/host.go
  code/go/ecs/http.go
  code/go/ecs/log.go
  code/go/ecs/network.go
  code/go/ecs/observer.go
  code/go/ecs/organization.go
  code/go/ecs/process.go
  code/go/ecs/related.go
  code/go/ecs/server.go
  code/go/ecs/service.go
  code/go/ecs/source.go
  code/go/ecs/url.go
  code/go/ecs/user.go
  code/go/ecs/user_agent.go
  fields.yml
  schema.csv
  schema.json
  schemas/agent.yml
  schemas/base.yml
  schemas/client.yml
  schemas/cloud.yml
  schemas/container.yml
  schemas/destination.yml
  schemas/ecs.yml
  schemas/error.yml
  schemas/event.yml
  schemas/file.yml
  schemas/geo.yml
  schemas/group.yml
  schemas/host.yml
  schemas/http.yml
  schemas/log.yml
  schemas/network.yml
  schemas/observer.yml
  schemas/organization.yml
  schemas/os.yml
  schemas/process.yml
  schemas/related.yml
  schemas/server.yml
  schemas/service.yml
  schemas/source.yml
  schemas/url.yml
  schemas/user.yml
  schemas/user_agent.yml
Labels: 1.0.0-ga, needs backport

#333 Clarify `geo` field set description.
  CHANGELOG.md
  README.md
  code/go/ecs/geo.go
  fields.yml
  schema.json
  schemas/geo.yml
Labels: 1.0.0-ga, needs backport

#329 Clarify the difference between @timestamp and event.created
  CHANGELOG.md
  README.md
  code/go/ecs/base.go
  code/go/ecs/event.go
  fields.yml
  schema.json
  schemas/base.yml
  schemas/event.yml
Labels: 1.0.0-ga, needs backport

#332 Make mentions of lowercasing refer to a general section of the docs.
  CHANGELOG.md
  README.md
  code/go/ecs/http.go
  code/go/ecs/network.go
  fields.yml
  schema.json
  schemas/http.yml
  schemas/network.yml
Labels: 1.0.0-ga, documentation, needs backport

#336 A new file generator
  Makefile
  README.md
  docs/generated-files.md
  docs/implementing.md
  docs/intro.md
  fields.yml
  generated/csv/fields.csv
  generated/ecs/fields_flat.yml
  generated/ecs/fields_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/legacy/schema.csv
  generated/legacy/template.json
  schemas/base.yml
  schemas/format.md
  scripts/__init__.py
  scripts/generator.py
  scripts/generators/__init__.py
  scripts/generators/csv_generator.py
  scripts/generators/es_template.py
  scripts/generators/intermediate_files.py
  scripts/schema_reader.py
  scripts/schemas.py
  scripts/tests/__init__.py
  scripts/tests/test_ecs_spec.py
  scripts/tests/test_es_template.py
  scripts/tests/test_schema_reader.py
  version
Labels: 1.0.0-ga, in progress, needs backport
