Repository elastic/ecs, pull requests merged in 2019-03, with the labels that each got.

#346 Simple steps to play with the Elasticsearch ECS templates
  generated/elasticsearch/README.md
Labels: 1.0.0-ga, needs backport

#348 Fix the actual cloud.provider example.
  README.md
  fields.yml
  generated/csv/fields.csv
  generated/ecs/fields_flat.yml
  generated/ecs/fields_nested.yml
  generated/legacy/schema.csv
  schema.json
  schemas/cloud.yml
Labels: 1.0.0-ga, needs backport

#350 Ecs version 1.0.0
  README.md
  docs/intro.md
  fields.yml
  schema.csv
  schemas/ecs.yml
  scripts/template.go
  template.json
Labels: 1.0.0-ga

#349 Clarify guidelines on ID fields.
  README.md
  docs/implementing.md
Labels: 1.0.0-ga, needs backport

#345 Add a 'how to populate ECS fields' section to readme...
  README.md
  docs/implementing.md
Labels: 1.0.0-ga, needs backport

#353 Backport: Remove the obsolete TODO file (#273)
  TODO.md
Labels: 1.0.0-ga, backport

#355 Backport: Make `user.group` a nesting of the `group` field set (#308)
  CHANGELOG.md
  README.md
  code/go/ecs/user.go
  fields.yml
  schema.csv
  schema.json
  schemas/group.yml
  schemas/user.yml
  template.json
Labels: 1.0.0-ga, backport

#356 Backport #319 to 1.0: Minor tweaks to contributor guidelines (#319)
  CONTRIBUTING.md
Labels: 1.0.0-ga, backport

#354 [1.0] Add a 'how to populate ECS fields' section to readme (#345)
  README.md
  docs/implementing.md
Labels: backport

#339 Change url.port datatype to long
  CHANGELOG.md
  README.md
  code/go/ecs/url.go
  fields.yml
  generated/csv/fields.csv
  generated/ecs/fields_flat.yml
  generated/ecs/fields_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/legacy/schema.csv
  schema.json
  schemas/url.yml
Labels: 1.0.0-ga, bug, needs backport

#344 Adjust the maturity warning for ECS to be aligned with GA / SemVer
  README.md
  docs/index.asciidoc
  docs/intro.md
Labels: 1.0.0-ga, needs backport

#360 Backport #329 to 1.0: Clarify the difference between @timestamp and event.created (#329)
  CHANGELOG.md
  README.md
  code/go/ecs/user.go
  fields.yml
  schema.json
  schemas/base.yml
  schemas/event.yml
Labels: 1.0.0-ga, backport

#358 Backport #325 to 1.0: clarify host definition wording (#325)
  CHANGELOG.md
Labels: 1.0.0-ga, backport

#363 Backport #331 to 1.0: Specify the `object_type` for field `labels`. (#331)
  CHANGELOG.md
  fields.yml
  schemas/base.yml
Labels: 1.0.0-ga, backport

#364 Backport #332 to 1.0: Make mentions of lowercasing refer to a general section of the docs. (#332)
  CHANGELOG.md
  README.md
  fields.yml
  schema.json
  schemas/http.yml
  schemas/network.yml
Labels: 1.0.0-ga, backport

#365 Backport #333 to 1.0: Clarify `geo` field set description. (#333)
  CHANGELOG.md
  README.md
  fields.yml
  schema.json
  schemas/geo.yml
Labels: 1.0.0-ga, backport

#359 [1.0] Clarify guidelines on ID fields. (#349)
  README.md
  docs/implementing.md
Labels: backport

#361 [1.0] Fix the actual cloud.provider example. (#348)
  README.md
  fields.yml
  schema.csv
  schema.json
  schemas/cloud.yml
Labels: backport

#366 Backport #336 to 1.0: A new file generator (#336)
  Makefile
  README.md
  docs/generated-files.md
  docs/implementing.md
  docs/intro.md
  fields.yml
  generated/csv/fields.csv
  generated/ecs/fields_flat.yml
  generated/ecs/fields_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/legacy/schema.csv
  generated/legacy/template.json
  schemas/base.yml
  schemas/format.md
  scripts/__init__.py
  scripts/generator.py
  scripts/generators/__init__.py
  scripts/generators/csv_generator.py
  scripts/generators/es_template.py
  scripts/generators/intermediate_files.py
  scripts/schema_reader.py
  scripts/schemas.py
  scripts/tests/__init__.py
  scripts/tests/test_ecs_spec.py
  scripts/tests/test_es_template.py
  scripts/tests/test_schema_reader.py
  version
Labels: 1.0.0-ga, backport

#368 Backport #346 to 1.0: Simple steps to experiment with the Elasticsearch ECS templates (#346)
  generated/elasticsearch/README.md
Labels: 1.0.0-ga, backport

#370 Backport #266 to 1.0: Convert ECS doc from MD to asciidoc guide: initial setup (#266)
  docs/contributing.asciidoc
  docs/conventions.asciidoc
  docs/fields-gen.asciidoc
  docs/fields.asciidoc
  docs/glossary.asciidoc
  docs/guidelines.asciidoc
  docs/index.asciidoc
  docs/use-cases.asciidoc
Labels: 1.0.0-ga, backport

#367 Backport #339 to 1.0: Change url.port datatype to long (#339)
  CHANGELOG.md
  README.md
  fields.yml
  generated/legacy/schema.csv
  schemas/url.yml
Labels: 1.0.0-ga, backport

#371 Backport #334 to 1.0: Phase 2 in conversion to asciidoc (#334)
  docs/conventions.asciidoc
  docs/convert.asciidoc
  docs/faq.asciidoc
  docs/fields-gen.asciidoc
  docs/fields.asciidoc
  docs/glossary.asciidoc
  docs/guidelines.asciidoc
  docs/index.asciidoc
  docs/use-cases.asciidoc
Labels: 1.0.0-ga, backport

#369 Backport #344 to 1.0: Adjust the maturity warning for ECS to be aligned with GA / SemVer (#344)
  README.md
  docs/index.asciidoc
  docs/intro.md
  generated/csv/fields.csv
  generated/ecs/fields_flat.yml
  generated/ecs/fields_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
Labels: 1.0.0-ga, backport

#372 Backport #275 to 1.0: Add automation around docs generation (#275)
  .gitignore
  .travis.yml
  Makefile
Labels: 1.0.0-ga, backport

#373 Backport #279 to 1.0: Add VERSION variable to Makefile (#279)
  Makefile
  generated/legacy/template.json
  scripts/template.go
Labels: 1.0.0-ga, backport

#374 Backport #287 to 1.0: Version Go deps and use Python virtualenv (#287)
  Makefile
  generated/legacy/template.json
  scripts/cmd/template/template.go
  scripts/go.mod
  scripts/go.sum
  scripts/requirements.txt
Labels: 1.0.0-ga, backport

#375 Set the ECS version to 1.0.0 in the 1.0 branch for the GA release
  Makefile
  generated/csv/fields.csv
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/legacy/template.json
  version
Labels: 1.0.0-ga

#378 Add changelog.next.md for all new entries
  CHANGELOG.md
  CHANGELOG.next.md
Labels: 1.0.0-docs

#379 Generate full Beats field definitions, including nested fields
  CHANGELOG.next.md
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/fields_flat.yml
  generated/ecs/fields_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  scripts/generator.py
  scripts/generators/beats.py
  scripts/schema_reader.py
  scripts/tests/test_ecs_spec.py
Labels: 1.0.0-docs, needs_backport

#380 Backport #378 to 1.0: Add changelog.next.md for all new entries (#378)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: 1.0.0-docs, backport

#381 Backport #379 to 1.0: Generate full Beats field definitions, including nested fields (#379)
  CHANGELOG.next.md
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/fields_flat.yml
  generated/ecs/fields_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  scripts/generator.py
  scripts/generators/beats.py
  scripts/schema_reader.py
  scripts/tests/test_ecs_spec.py
Labels: 1.0.0-docs, backport

#382 Backport #249 to 1.0: Add code generator for Go (#249)
  CHANGELOG.next.md
  Makefile
  code/README.md
  code/go/ecs/README.md
  code/go/ecs/agent.go
  code/go/ecs/base.go
  code/go/ecs/client.go
  code/go/ecs/cloud.go
  code/go/ecs/container.go
  code/go/ecs/destination.go
  code/go/ecs/doc.go
  code/go/ecs/ecs.go
  code/go/ecs/error.go
  code/go/ecs/event.go
  code/go/ecs/file.go
  code/go/ecs/geo.go
  code/go/ecs/group.go
  code/go/ecs/host.go
  code/go/ecs/http.go
  code/go/ecs/log.go
  code/go/ecs/network.go
  code/go/ecs/observer.go
  code/go/ecs/organization.go
  code/go/ecs/os.go
  code/go/ecs/process.go
  code/go/ecs/related.go
  code/go/ecs/server.go
  code/go/ecs/service.go
  code/go/ecs/source.go
  code/go/ecs/url.go
  code/go/ecs/user.go
  code/go/ecs/user_agent.go
  code/go/ecs/version.go
  scripts/cmd/gocodegen/gocodegen.go
  scripts/go.mod
  scripts/go.sum
Labels: 1.0.0-docs, backport

#383 Backport #296 to 1.0: Generate process.args as []string in Go code (#296)
  code/go/ecs/process.go
  scripts/cmd/gocodegen/gocodegen.go
Labels: 1.0.0-docs, backport

#347 Generator for asciidoc representation of all ECS fields
  Makefile
  docs/field-details.asciidoc
  docs/fields-gen.asciidoc
  docs/fields.asciidoc
  generated/ecs/fields_flat.yml
  generated/ecs/fields_nested.yml
  generated/legacy/fields.yml
  schemas/event.yml
  scripts/generator.py
  scripts/generators/asciidoc_fields.py
  scripts/generators/beats.py
  scripts/generators/ecs_helpers.py
  scripts/generators/es_template.py
  scripts/generators/intermediate_files.py
  scripts/schema_reader.py
  scripts/tests/test_ecs_helpers.py
  scripts/tests/test_ecs_spec.py
  scripts/tests/test_es_template.py
  scripts/tests/test_schema_reader.py
Labels: 1.0.0-docs, documentation, needs_backport, review

#390 Changelog for #347
  CHANGELOG.next.md
Labels: 1.0.0-docs, needs_backport

#389 Wrap long definitions to less than 100 chars per line.
  README.md
  generated/beats/fields.ecs.yml
  generated/ecs/fields_nested.yml
  generated/legacy/fields.yml
  schema.json
  schemas/client.yml
  schemas/event.yml
  schemas/file.yml
  schemas/host.yml
  schemas/observer.yml
  schemas/related.yml
  schemas/server.yml
Labels: 1.0.0-docs, needs_backport

#391 Fix asciidoc rendering after #347 + #389 :eyeroll:
  docs/field-details.asciidoc
Labels: 1.0.0-docs, needs_backport

#392 Backport #347 and #390 to 1.0: Generator for asciidoc representation of all ECS fields (#347)
  CHANGELOG.next.md
  Makefile
  docs/field-details.asciidoc
  docs/fields-gen.asciidoc
  docs/fields.asciidoc
  fields.yml
  generated/ecs/fields_flat.yml
  generated/ecs/fields_nested.yml
  schemas/event.yml
  scripts/generator.py
  scripts/generators/asciidoc_fields.py
  scripts/generators/beats.py
  scripts/generators/ecs_helpers.py
  scripts/generators/es_template.py
  scripts/generators/intermediate_files.py
  scripts/schema_reader.py
  scripts/tests/test_ecs_helpers.py
  scripts/tests/test_ecs_spec.py
  scripts/tests/test_es_template.py
  scripts/tests/test_schema_reader.py
Labels: 1.0.0-docs, backport

#397 [DOCS] Adds book title
  docs/index.asciidoc
Labels: 1.0.0-docs, needs_backport

#396 Backport #389 to 1.0: Wrap long definitions to less than 100 chars per line. (#389)
  README.md
  docs/field-details.asciidoc
  fields.yml
  generated/beats/fields.ecs.yml
  generated/ecs/fields_nested.yml
  schemas/client.yml
  schemas/event.yml
  schemas/file.yml
  schemas/host.yml
  schemas/observer.yml
  schemas/related.yml
  schemas/server.yml
Labels: 1.0.0-docs, backport

#398 Backport #397 to 1.0: [DOCS] Adds book title (#397)
  docs/index.asciidoc
Labels: 1.0.0-docs, backport

#399 Remove most legacy generated files.
  CHANGELOG.next.md
  Makefile
  generated/legacy/fields.yml
  generated/legacy/fields_header.yml
  generated/legacy/schema.csv
  scripts/schemas.py
Labels: 1.0.0-docs, needs_backport

#402 Backport #399 to 1.0: Remove most legacy generated files. (#399)
  Makefile
  generated/legacy/schema.csv
  scripts/schemas.py
Labels: 1.0.0-docs, backport

#400 Take 2 of readme reset PR
  CONTRIBUTING.md
  Makefile
  README.md
  docs/about.md
  docs/generated-files.md
  docs/implementing.md
  docs/intro.md
  docs/use-cases-header.md
  generated/README.md
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/README.md
  scripts/generators/intermediate_files.py
Labels: 1.0.0-docs, needs_backport

#404 Fix version at the top of the docs.
  docs/index.asciidoc
Labels: 1.0.0-docs

#406 Fix links to reused fields at the bottom of field set detail pages.
  docs/field-details.asciidoc
  scripts/generators/asciidoc_fields.py
Labels: 1.0.0-docs, needs_backport

#407 Backport #406 to 1.0: Fix links to reused fields at the bottom of field set detail pages
  docs/field-details.asciidoc
  scripts/generators/asciidoc_fields.py
Labels: 1.0.0-docs, backport

#405 Backport #400 to 1.0: Point README to the new official docs and other contributor-centric doc (#400)
  CONTRIBUTING.md
  Makefile
  README.md
  docs/about.md
  docs/generated-files.md
  docs/implementing.md
  docs/intro.md
  docs/use-cases-header.md
  generated/README.md
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/README.md
  scripts/generators/intermediate_files.py
Labels: 1.0.0-docs, backport
