Repository elastic/ecs, pull requests merged in 2019-01, with the labels that each got.

#296 Generate process.args as []string in Go code
  code/go/ecs/process.go
  scripts/cmd/gocodegen/gocodegen.go
Labels: :codegen, review

#298 Update PyYAML to 4.2b1
  scripts/requirements.txt
Labels: review

#308 Make `user.group` a nesting of the `group` field set
  CHANGELOG.md
  README.md
  code/go/ecs/user.go
  fields.yml
  schema.csv
  schema.json
  schemas/group.yml
  schemas/user.yml
  template.json
Labels: 1.0.0-ga, bug, needs backport
