Repository elastic/ecs, pull requests merged in 2020-08, with the labels that each got.

#905 clean up event.type and event.category
  docs/using-getting-started.asciidoc
Labels: documentation

#906 [1.5] Add getting started doc (#888)
  docs/images/ecs-getting-started-dashboard.png
  docs/index.asciidoc
  docs/using-getting-started.asciidoc
  docs/using.asciidoc
Labels: backport, documentation

#903 updating slack and discuss
  CONTRIBUTING.md
Labels: documentation

#907 Add event.reason field
  CHANGELOG.next.md
  code/go/ecs/event.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/event.yml
Labels: 1.6.0, ready

#916 Replace a few direct links in the docs with shortcuts
  docs/using-getting-started.asciidoc
Labels: 1.5.0, 1.6.0, needs_backport

#910 Use appropriate reserved domain for example URLs
  CHANGELOG.next.md
  code/go/ecs/client.go
  code/go/ecs/destination.go
  code/go/ecs/dns.go
  code/go/ecs/event.go
  code/go/ecs/server.go
  code/go/ecs/source.go
  code/go/ecs/url.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/client.yml
  schemas/destination.yml
  schemas/dns.yml
  schemas/event.yml
  schemas/server.yml
  schemas/source.yml
  schemas/tls.yml
  schemas/url.yml
  schemas/x509.yml
Labels: 1.5.0, 1.6.0, documentation, needs_backport, ready

#913 add related.hosts
  CHANGELOG.next.md
  code/go/ecs/related.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/related.yml
Labels: 1.6.0

#919 [1.5] Use appropriate reserved domain for example URLs (#910)
  CHANGELOG.next.md
  code/go/ecs/client.go
  code/go/ecs/destination.go
  code/go/ecs/dns.go
  code/go/ecs/event.go
  code/go/ecs/server.go
  code/go/ecs/source.go
  code/go/ecs/url.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/client.yml
  schemas/destination.yml
  schemas/dns.yml
  schemas/event.yml
  schemas/server.yml
  schemas/source.yml
  schemas/tls.yml
  schemas/url.yml
Labels: backport

#925 [1.6] add related.hosts (#913)
  CHANGELOG.md
  code/go/ecs/related.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/related.yml
Labels: backport

#924 [1.x] add related.hosts (#913)
  CHANGELOG.next.md
  code/go/ecs/related.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/related.yml
Labels: backport

#918 Backport #916 to 1.5: Replace a few direct links in the docs with shortcuts
  docs/using-getting-started.asciidoc
Labels: 1.5.0, backport

#933 Move changelog entries to more appropriate subsections
  CHANGELOG.md
Labels: 1.6.0

#908 [DOCS] Fixes SIEM links
  docs/products-solutions.asciidoc
  docs/using-getting-started.asciidoc
Labels: 1.3.1, 1.4.0, 1.5.0, 1.6.0, 1.x, documentation, needs_backport

#936 [1.x][DOCS] Fixes SIEM links
  docs/products-solutions.asciidoc
  docs/using-getting-started.asciidoc
Labels: backport, documentation

#926 [1.6][DOCS] Fixes SIEM links
  docs/products-solutions.asciidoc
  docs/using-getting-started.asciidoc
Labels: backport, documentation

#912 [1.4][DOCS] Fixes SIEM links
  docs/products-solutions.asciidoc
Labels: backport, documentation

#927 [1.3][DOCS] Fixes SIEM links
  docs/products-solutions.asciidoc
Labels: backport, documentation

#911 [1.5][DOCS] Fixes SIEM links
  docs/products-solutions.asciidoc
  docs/using-getting-started.asciidoc
Labels: backport, documentation

#934 Improve backport support
  .backportrc.json
  CONTRIBUTING.md
Labels: ready, review

#897 Consolidate field-details doc template
  CHANGELOG.next.md
  docs/field-details.asciidoc
  scripts/generators/asciidoc_fields.py
  scripts/templates/field_details.j2
  scripts/templates/field_details/acceptable_value_names.j2
  scripts/templates/field_details/field_reuse_section.j2
  scripts/templates/field_details/nestings_row.j2
  scripts/templates/field_details/nestings_table_header.j2
  scripts/templates/field_details/row.j2
  scripts/templates/field_details/table_header.j2
  scripts/templates/field_values.j2
  scripts/templates/fields.j2
  scripts/tests/test_asciidoc_fields.py
Labels: 1.7.0, 1.x, needs_backport, review

#946 [1.x] Consolidate field-details doc template (#897)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  scripts/generators/asciidoc_fields.py
  scripts/templates/field_details.j2
  scripts/templates/field_details/acceptable_value_names.j2
  scripts/templates/field_details/field_reuse_section.j2
  scripts/templates/field_details/nestings_row.j2
  scripts/templates/field_details/nestings_table_header.j2
  scripts/templates/field_details/row.j2
  scripts/templates/field_details/table_header.j2
  scripts/templates/field_values.j2
  scripts/templates/fields.j2
  scripts/tests/test_asciidoc_fields.py
Labels: backport

#944 Add http.[request|response].mime_type
  CHANGELOG.next.md
  code/go/ecs/http.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/http.yml
Labels: 1.7.0, 1.x, needs_backport

#949 [1.x] Add http.[request|response].mime_type (#944)
  CHANGELOG.next.md
  code/go/ecs/http.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/http.yml
Labels: backport

#920 bumping version for the 1.6 release branch
  code/go/ecs/version.go
  docs/fields.asciidoc
  docs/index.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  version
Labels: ready

#952 [master] Move changelog entries to more appropriate subsections (#933)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: 1.x, forward_port, needs_backport

#953 [1.x] Cut 1.6 Changelog (#933) (#952)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: backport

#951 Add threat.technique.subtechnique
  CHANGELOG.next.md
  code/go/ecs/threat.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/threat.yml
Labels: 1.7.0, needs_backport, ready

#937 Introduce `--strict` flag
  CHANGELOG.next.md
  Makefile
  USAGE.md
  scripts/generator.py
  scripts/generators/ecs_helpers.py
  scripts/schema/cleaner.py
  scripts/tests/unit/test_schema_cleaner.py
Labels: ready

#956 [1.x] Add threat.technique.subtechnique (#951)
  CHANGELOG.next.md
  code/go/ecs/threat.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/threat.yml
Labels: backport
