Repository elastic/ecs, pull requests merged in 2020-11, with the labels that each got.

#1048 Change the index pattern in the sample template.
  CHANGELOG.md
  experimental/generated/elasticsearch/7/template.json
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/README.md
  scripts/generators/es_template.py
Labels: 1.7.0, 1.8.0, 1.x, needs_backport

#1068 [1.x] Change the index pattern in the sample template.
  CHANGELOG.md
  experimental/generated/elasticsearch/7/template.json
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/README.md
  scripts/generators/es_template.py
Labels: backport

#1069 [1.7] Change the index pattern in the sample template.
  CHANGELOG.md
  experimental/generated/elasticsearch/7/template.json
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/README.md
  scripts/generators/es_template.py
Labels: backport

#1074 Docs: Add ifeval to products page
  docs/products-solutions.asciidoc
Labels: 1.3, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.x, documentation, needs_backport

#1073 Docs: Add ifeval for 7.10 release
  docs/using-getting-started.asciidoc
Labels: 1.5.0, 1.6.0, 1.7.0, 1.x, documentation, needs_backport

#1079 [1.x] Prepare link to Logs docs changing with the 7.10 release in "getting-started" (#1073)
  docs/using-getting-started.asciidoc
Labels: backport

#1080 [1.7] Prepare link to Logs docs changing with the 7.10 release in "getting-started" (#1073)
  docs/using-getting-started.asciidoc
Labels: backport

#1081 [1.6] Prepare link to Logs docs changing with the 7.10 release in "getting-started" (#1073)
  docs/using-getting-started.asciidoc
Labels: backport

#1083 [1.x] Prepare link to Logs docs changing with the 7.10 release in "products-solutions" page (#1074)
  docs/products-solutions.asciidoc
Labels: backport

#1084 [1.7] Prepare link to Logs docs changing with the 7.10 release in "products-solutions" page (#1074)
  docs/products-solutions.asciidoc
Labels: backport

#1085 [1.6] Prepare link to Logs docs changing with the 7.10 release in "products-solutions" page (#1074)
  docs/products-solutions.asciidoc
Labels: backport

#1089 [1.5] Add [discrete] headers to Asciidoc generator
  scripts/generators/asciidoc_fields.py
Labels: 1.3.0, 1.4.0, needs_backport

#1090 [1.6] Remove `expected_event_types` from protocol (#964)
  docs/field-values.asciidoc
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: backport

#1091 [1.4] Add [discrete] headers to Asciidoc generator (#1089)
  scripts/generators/asciidoc_fields.py
Labels: backport

#1092 [1.3] Add [discrete] headers to Asciidoc generator (#1089)
  scripts/generators/asciidoc_fields.py
Labels: backport

#1082 [1.5] Prepare link to Logs docs changing with the 7.10 release in "getting-started" (#1073)
  docs/using-getting-started.asciidoc
Labels: backport

#1086 [1.5] Prepare link to Logs docs changing with the 7.10 release in "products-solutions" page (#1074)
  docs/products-solutions.asciidoc
Labels: backport

#1093 [1.x] Add event.category session. (#1049)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  docs/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: backport

#1087 [1.4] Prepare link to Logs docs changing with the 7.10 release in "products-solutions" page (#1074)
  docs/products-solutions.asciidoc
Labels: backport

#1088 [1.3] Prepare link to Logs docs changing with the 7.10 release in "products-solutions" page (#1074)
  docs/products-solutions.asciidoc
Labels: backport

#1094 [1.x] Add event.category registry (#1040)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  docs/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: backport

#1037 [RFC] Cyber Threat Intelligence Fields Stage 1
  rfcs/text/0008-threat-intel.md
Labels: RFC

#1063 Add --ref support for experimental artifacts
  CHANGELOG.md
  USAGE.md
  scripts/generator.py
  scripts/generators/ecs_helpers.py
  scripts/schema/loader.py
  scripts/tests/test_ecs_helpers.py
  scripts/tests/unit/test_schema_loader.py
Labels: 1.7.0, 1.x, needs_backport, ready

#1101 [1.x] Add --ref support for experimental artifacts (#1063)
  CHANGELOG.md
  USAGE.md
  scripts/generator.py
  scripts/generators/ecs_helpers.py
  scripts/schema/loader.py
  scripts/tests/test_ecs_helpers.py
  scripts/tests/unit/test_schema_loader.py
Labels: backport

#1102 [1.7] Add --ref support for experimental artifacts (#1063)
  CHANGELOG.md
  USAGE.md
  scripts/generator.py
  scripts/generators/ecs_helpers.py
  scripts/schema/loader.py
  scripts/tests/test_ecs_helpers.py
  scripts/tests/unit/test_schema_loader.py
Labels: backport

#1053 Remove experimental event.original definition
  CHANGELOG.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/schemas/event.yml
Labels: 1.7.0, 1.x, needs_backport, ready

#1104 [1.x] Remove experimental event.original definition (#1053)
  CHANGELOG.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/schemas/event.yml
Labels: backport

#1105 [1.7] Remove experimental event.original definition (#1053)
  CHANGELOG.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/schemas/event.yml
Labels: backport

#1103 Add missing `process.thread.name` to experimental definitions
  CHANGELOG.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/schemas/process.yml
Labels: 1.7.0, 1.x, needs_backport

#1106 [1.x] Add missing `process.thread.name` to experimental definitions (#1103)
  CHANGELOG.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/schemas/process.yml
Labels: backport

#1107 [1.7] Add missing `process.thread.name` to experimental definitions (#1103)
  CHANGELOG.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/schemas/process.yml
Labels: backport

#1015 [RFC] Wildcard - stage 3 proposal
  rfcs/text/0001-wildcard-data-type.md
  rfcs/text/0001/event.yml
  rfcs/text/0001/process.yml
Labels: RFC

#980 [RFC] data_stream fields
  rfcs/text/0009-data_stream-fields.md
Labels: RFC

#1017 [RFC] Multiple users in an event, stage 3 PR
  rfcs/text/0007-multiple-users.md
Labels: RFC

#1115 Remove index parameter for wildcard fields
  CHANGELOG.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  schemas/README.md
  scripts/schema/cleaner.py
  scripts/tests/unit/test_schema_cleaner.py
Labels: 1.7.0, 1.x, needs_backport

#1119 [1.x] Remove index parameter for wildcard fields (#1115)
  CHANGELOG.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  schemas/README.md
  scripts/schema/cleaner.py
  scripts/tests/unit/test_schema_cleaner.py
Labels: backport

#1120 [1.7] Remove index parameter for wildcard fields (#1115)
  CHANGELOG.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  schemas/README.md
  scripts/schema/cleaner.py
  scripts/tests/unit/test_schema_cleaner.py
Labels: backport

#1118 Add dns.answer object into experimental schema
  CHANGELOG.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/schemas/dns.yml
Labels: 1.7.0, 1.x, needs_backport

#1121 [1.x] Add dns.answer object into experimental schema (#1118)
  CHANGELOG.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/schemas/dns.yml
Labels: backport

#1122 [1.7] Add dns.answer object into experimental schema (#1118)
  CHANGELOG.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/schemas/dns.yml
Labels: backport

#1114 Clarify x509 definition guidance for network events with only one cert
  CHANGELOG.md
  code/go/ecs/x509.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_nested.yml
  schemas/x509.yml
Labels: 1.7.0, 1.x, needs_backport

#1117 Indicate when artifacts include experimental changes
  CHANGELOG.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/elasticsearch/7/template.json
  scripts/generator.py
  scripts/schema/loader.py
Labels: 1.7.0, 1.x, needs_backport

#1123 [1.x] Clarify x509 definition guidance for network events with only one cert (#1114)
  CHANGELOG.md
  code/go/ecs/x509.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_nested.yml
  schemas/x509.yml
Labels: backport

#1124 [1.7] Clarify x509 definition guidance for network events with only one cert (#1114)
  CHANGELOG.md
  code/go/ecs/x509.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_nested.yml
  schemas/x509.yml
Labels: backport

#1125 [1.x] Indicate when artifacts include experimental changes (#1117)
  CHANGELOG.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/elasticsearch/7/template.json
  scripts/generator.py
  scripts/schema/loader.py
Labels: backport

#1126 [1.7] Indicate when artifacts include experimental changes (#1117)
  CHANGELOG.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/elasticsearch/7/template.json
  scripts/generator.py
  scripts/schema/loader.py
Labels: backport

#1111 Add os.type field
  CHANGELOG.next.md
  code/go/ecs/os.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/os.yml
Labels: 1.8.0, 1.x, needs_backport, ready

#1130 [1.x] Add os.type field, with list of allowed values (#1111)
  CHANGELOG.next.md
  code/go/ecs/os.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/os.yml
Labels: backport

#1112 Add support for constant_keyword's 'value' parameter
  CHANGELOG.next.md
  scripts/generators/es_template.py
  scripts/tests/test_es_template.py
Labels: 1.8.0, 1.x, needs_backport, ready

#1132 [1.x] Add support for constant_keyword's 'value' parameter (#1112)
  CHANGELOG.next.md
  scripts/generators/es_template.py
  scripts/tests/test_es_template.py
Labels: backport

#1051 Beta label support
  CHANGELOG.next.md
  schemas/README.md
  scripts/generators/asciidoc_fields.py
  scripts/generators/ecs_helpers.py
  scripts/schema/cleaner.py
  scripts/schema/finalizer.py
  scripts/templates/field_details.j2
  scripts/tests/unit/test_schema_finalizer.py
Labels: 1.8.0, 1.x, needs_backport, ready

#1133 [1.x] Beta label support (#1051)
  CHANGELOG.next.md
  schemas/README.md
  scripts/generators/asciidoc_fields.py
  scripts/generators/ecs_helpers.py
  scripts/schema/cleaner.py
  scripts/schema/finalizer.py
  scripts/templates/field_details.j2
  scripts/tests/unit/test_schema_finalizer.py
Labels: backport

#1134 Docs: Remove ifeval from getting-starting
  docs/using-getting-started.asciidoc
Labels: 1.5.0, 1.6.0, 1.7.0, 1.x, documentation, needs_backport

#1135 Docs: Remove ifeval from products page
  docs/products-solutions.asciidoc
Labels: 1.3, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.x, documentation, needs_backport

#1136 [1.x] Backport #1134 and #1135
  docs/products-solutions.asciidoc
  docs/using-getting-started.asciidoc
Labels: backport

#1137 [1.7] Backport #1134 and #1135
  docs/products-solutions.asciidoc
  docs/using-getting-started.asciidoc
Labels: backport

#1138 [1.6] Backport #1134 and #1135
  docs/products-solutions.asciidoc
  docs/using-getting-started.asciidoc
Labels: backport

#1139 [1.5] Backport #1134 and #1135
  docs/products-solutions.asciidoc
  docs/using-getting-started.asciidoc
Labels: backport

#1140 [1.4] Remove temporary ifeval from products page, add link to Metrics (#1135)
  docs/products-solutions.asciidoc
Labels: backport

#1141 [1.3] Remove temporary ifeval from products page, add link to Metrics (#1135)
  docs/products-solutions.asciidoc
Labels: backport

#1146 Remove an incorrect `event.type` from the 'converting' guide
  docs/converting.asciidoc
Labels: 1.7.0, 1.x, needs_backport

#1147 Mention Logstash support for ECS in the 'products' page
  docs/products-solutions.asciidoc
Labels: 1.7.0, 1.x, needs_backport

#1149 Two small documentation backports
  docs/converting.asciidoc
  docs/products-solutions.asciidoc
Labels: backport

#1150 Two small documentation backports
  docs/converting.asciidoc
  docs/products-solutions.asciidoc
Labels: backport

#1151 Reinforce the exclusion of the leading dot from url.extension
  code/go/ecs/url.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/url.yml
Labels: 1.7, needs_backport

#1152 [1.x] Reinforce the exclusion of the leading dot from url.extension (#1151)
  code/go/ecs/url.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/url.yml
Labels: backport

#1153 [1.7] Reinforce the exclusion of the leading dot from url.extension (#1151)
  code/go/ecs/url.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/url.yml
Labels: backport

#1148 Make all fields linkable directly via an HTML ID
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  scripts/schema/finalizer.py
  scripts/templates/field_details.j2
  scripts/tests/unit/test_schema_finalizer.py
Labels: 1.7.0, 1.x, needs_backport

#1154 [1.x] Make all fields linkable directly via an HTML ID (#1148)
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  scripts/schema/finalizer.py
  scripts/templates/field_details.j2
  scripts/tests/unit/test_schema_finalizer.py
Labels: backport

#1155 [1.7] Make all fields linkable directly via an HTML ID (#1148)
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  scripts/schema/finalizer.py
  scripts/templates/field_details.j2
  scripts/tests/unit/test_schema_finalizer.py
Labels: backport

#999 [RFC] E-Mail
  rfcs/text/0008-email.md
Labels: 1.8.0, RFC
