Repository elastic/ecs, pull requests merged in 2020-10, with the labels that each got.

#914 [RFC] Multiple users in an event
  rfcs/0000-rfc-template.md
  rfcs/text/0007-multiple-users.md
  rfcs/text/0007/user.yml
  schemas/user.yml
Labels: 7.11 candidate, Feature: ECS, RFC, Team: ECS, ready, v7.11.0

#991 Add --oss flag to the ECS generator script
  CHANGELOG.next.md
  USAGE.md
  scripts/generator.py
  scripts/schema/oss.py
  scripts/tests/unit/test_schema_oss.py
Labels: 1.7.0, 1.x, needs_backport

#981 Uniformity across domain name breakdown fields
  CHANGELOG.next.md
  code/go/ecs/client.go
  code/go/ecs/destination.go
  code/go/ecs/server.go
  code/go/ecs/source.go
  code/go/ecs/url.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/client.yml
  schemas/destination.yml
  schemas/server.yml
  schemas/source.yml
  schemas/url.yml
Labels: 1.7.0, needs_backport

#994 [1.x] Uniformity across domain name breakdown fields (#981)
  CHANGELOG.next.md
  code/go/ecs/client.go
  code/go/ecs/destination.go
  code/go/ecs/server.go
  code/go/ecs/source.go
  code/go/ecs/url.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/client.yml
  schemas/destination.yml
  schemas/server.yml
  schemas/source.yml
  schemas/url.yml
Labels: backport

#970 [RFC] Wildcard - stage 2 proposal
  rfcs/text/0001-wildcard-data-type.md
  rfcs/text/0001/agent.yml
  rfcs/text/0001/as.yml
  rfcs/text/0001/client.yml
  rfcs/text/0001/destination.yml
  rfcs/text/0001/dns.yml
  rfcs/text/0001/error.yml
  rfcs/text/0001/event.yml
  rfcs/text/0001/file.yml
  rfcs/text/0001/geo.yml
  rfcs/text/0001/host.yml
  rfcs/text/0001/http.yml
  rfcs/text/0001/log.yml
  rfcs/text/0001/organization.yml
  rfcs/text/0001/os.yml
  rfcs/text/0001/pe.yml
  rfcs/text/0001/process.yml
  rfcs/text/0001/registry.yml
  rfcs/text/0001/server.yml
  rfcs/text/0001/source.yml
  rfcs/text/0001/tls.yml
  rfcs/text/0001/url.yml
  rfcs/text/0001/user.yml
  rfcs/text/0001/user_agent.yml
  rfcs/text/0001/x509.yml
Labels: RFC

#995 [1.x] Add --oss flag to the ECS generator script (#991)
  CHANGELOG.next.md
  USAGE.md
  scripts/generator.py
  scripts/schema/oss.py
  scripts/tests/unit/test_schema_oss.py
Labels: backport

#945 Add network directions ingress and egress
  CHANGELOG.next.md
  code/go/ecs/network.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/network.yml
Labels: 1.7.0, 1.x, 7.11 candidate, Feature: ECS, Team: ECS, needs_backport, ready, v7.11.0

#997 [1.x] Add network directions ingress and egress (#945)
  CHANGELOG.next.md
  code/go/ecs/network.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/network.yml
Labels: backport

#987 Mention ECS Mapper in the main documentation
  docs/converting.asciidoc
Labels: documentation

#1000 [1.x] Mention ECS Mapper in the main documentation (#987)
  docs/converting.asciidoc
Labels: backport

#993 Introduce experimental artifacts
  .gitignore
  Makefile
  experimental/README.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/schemas/agent.yml
  experimental/schemas/as.yml
  experimental/schemas/client.yml
  experimental/schemas/destination.yml
  experimental/schemas/dns.yml
  experimental/schemas/error.yml
  experimental/schemas/event.yml
  experimental/schemas/file.yml
  experimental/schemas/geo.yml
  experimental/schemas/host.yml
  experimental/schemas/http.yml
  experimental/schemas/log.yml
  experimental/schemas/organization.yml
  experimental/schemas/os.yml
  experimental/schemas/pe.yml
  experimental/schemas/process.yml
  experimental/schemas/registry.yml
  experimental/schemas/server.yml
  experimental/schemas/source.yml
  experimental/schemas/tls.yml
  experimental/schemas/url.yml
  experimental/schemas/user.yml
  experimental/schemas/user_agent.yml
  experimental/schemas/x509.yml
Labels: 1.7.0, 1.x, needs_backport

#1001 [1.x] Introduce experimental artifacts (#993)
  .gitignore
  Makefile
  experimental/README.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/schemas/agent.yml
  experimental/schemas/as.yml
  experimental/schemas/client.yml
  experimental/schemas/destination.yml
  experimental/schemas/dns.yml
  experimental/schemas/error.yml
  experimental/schemas/event.yml
  experimental/schemas/file.yml
  experimental/schemas/geo.yml
  experimental/schemas/host.yml
  experimental/schemas/http.yml
  experimental/schemas/log.yml
  experimental/schemas/organization.yml
  experimental/schemas/os.yml
  experimental/schemas/pe.yml
  experimental/schemas/process.yml
  experimental/schemas/registry.yml
  experimental/schemas/server.yml
  experimental/schemas/source.yml
  experimental/schemas/tls.yml
  experimental/schemas/url.yml
  experimental/schemas/user.yml
  experimental/schemas/user_agent.yml
  experimental/schemas/x509.yml
Labels: backport

#1002 [1.6][DOCS] Adding discrete markers
  docs/field-details.asciidoc
  scripts/templates/field_details/field_reuse_section.j2
  scripts/templates/field_details/nestings_table_header.j2
  scripts/templates/field_details/table_header.j2
Labels: backport, documentation

#1003 [1.5][DOCS] Adding discrete markers
  docs/field-details.asciidoc
Labels: backport, documentation

#1004 [1.4][DOCS] Adding discrete markers
  docs/field-details.asciidoc
Labels: backport, documentation

#1005 [1.3][DOCS] Adding discrete headers
  docs/field-details.asciidoc
Labels: backport, documentation

#1006 [1.2][DOCS] Adding discrete markers
  docs/field-details.asciidoc
Labels: backport, documentation

#1007 [1.1][DOCS] Adding discrete markers
  docs/field-details.asciidoc
Labels: backport, documentation

#1008 [1.0][DOCS] Add discrete markers
  docs/field-details.asciidoc
Labels: backport, documentation

#1010 Cut 1.7 changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: 1.7.0

#1016 Clarify that file extension should exclude the dot.
  CHANGELOG.md
  code/go/ecs/file.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/file.yml
Labels: 1.6.0, 1.7.0, 1.x, needs_backport

#1020 [1.x] Clarify that file extension should exclude the dot. (#1016)
  CHANGELOG.md
  code/go/ecs/file.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/file.yml
Labels: backport

#1021 [1.7] Clarify that file extension should exclude the dot. (#1016)
  CHANGELOG.md
  code/go/ecs/file.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/file.yml
Labels: backport

#1022 [1.6] Clarify that file extension should exclude the dot. (#1016)
  CHANGELOG.md
  code/go/ecs/file.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/file.yml
Labels: backport

#988 Add usage docs section
  CHANGELOG.next.md
  Makefile
  docs/usage/README.md
  scripts/generators/asciidoc_fields.py
  scripts/generators/ecs_helpers.py
  scripts/templates/field_details.j2
  scripts/tests/test_asciidoc_fields.py
Labels: 1.7.0, ready

#1024 [1.x] Add usage docs section (#988)
  CHANGELOG.md
  Makefile
  docs/usage/README.md
  scripts/generators/asciidoc_fields.py
  scripts/generators/ecs_helpers.py
  scripts/templates/field_details.j2
  scripts/tests/test_asciidoc_fields.py
Labels: backport

#1026 [1.7] Add usage docs section (#988)
  CHANGELOG.md
  Makefile
  docs/usage/README.md
  scripts/generators/asciidoc_fields.py
  scripts/generators/ecs_helpers.py
  scripts/templates/field_details.j2
  scripts/tests/test_asciidoc_fields.py
Labels: backport

#1031 Set the correct merge date for RFC 0005 stage 1
  rfcs/text/0005-host-metric-fields.md
Labels: RFC

#986 [RFC] Threat intelligence
  rfcs/text/0008-threat-intel.md
Labels: RFC

#877 feat: include alias path when generating template
  CHANGELOG.next.md
  schemas/README.md
  scripts/generators/beats.py
  scripts/generators/es_template.py
  scripts/schema/cleaner.py
  scripts/tests/test_es_template.py
  scripts/tests/unit/test_schema_cleaner.py
Labels: ready, review

#1035 [1.x] feat: include alias path when generating template (#877)
  CHANGELOG.next.md
  schemas/README.md
  scripts/generators/beats.py
  scripts/generators/es_template.py
  scripts/schema/cleaner.py
  scripts/tests/test_es_template.py
  scripts/tests/unit/test_schema_cleaner.py
Labels: backport

#1036 Add TLDR example to USAGE.md and full example in `usage-example/`
  USAGE.md
  scripts/generator.py
  usage-example/README.md
  usage-example/fields/custom/acme.yml
  usage-example/fields/mapping-settings.json
  usage-example/fields/subset.yml
  usage-example/fields/template-settings.json
  usage-example/generated/beats/fields.ecs.yml
  usage-example/generated/csv/fields.csv
  usage-example/generated/ecs/ecs_flat.yml
  usage-example/generated/ecs/ecs_nested.yml
  usage-example/generated/ecs/subset/web_logs/ecs_flat.yml
  usage-example/generated/ecs/subset/web_logs/ecs_nested.yml
  usage-example/generated/elasticsearch/6/template.json
  usage-example/generated/elasticsearch/7/template.json
Labels: documentation

#1041 New default make task that generates main and experimental artifacts.
  Makefile
Labels: 1.8.0

#1042 Add support for `scaling_factor` in the generator
  CHANGELOG.next.md
  scripts/generators/beats.py
  scripts/generators/es_template.py
  scripts/schema/cleaner.py
  scripts/tests/test_es_template.py
  scripts/tests/unit/test_schema_cleaner.py
Labels: 1.8.0, 1.x, needs_backport

#1046 Add fallback for constant_keyword
  CHANGELOG.next.md
  scripts/schema/oss.py
  scripts/tests/unit/test_schema_oss.py
Labels: 1.7.0, 1.8.0, 1.x, needs_backport

#1049 Add event.category session.
  CHANGELOG.next.md
  docs/field-details.asciidoc
  docs/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: 1.8.0, needs_backport

#1040 Add event.category registry
  CHANGELOG.next.md
  docs/field-details.asciidoc
  docs/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: 1.8.0, 1.x, needs_backport

#1055 [1.x] Add support for `scaling_factor` in the generator (#1042)
  CHANGELOG.next.md
  scripts/generators/beats.py
  scripts/generators/es_template.py
  scripts/schema/cleaner.py
  scripts/tests/test_es_template.py
  scripts/tests/unit/test_schema_cleaner.py
Labels: backport

#1056 [1.x] Add fallback for constant_keyword (#1046)
  CHANGELOG.next.md
  scripts/schema/oss.py
  scripts/tests/unit/test_schema_oss.py
Labels: backport

#1057 [1.x] Add wildcard type support to go code generator (#1050)
  CHANGELOG.next.md
  scripts/cmd/gocodegen/gocodegen.go
Labels: backport

#1060 [1.x] New default make task that generates main and experimental artifacts. (#1041)
  Makefile
Labels: backport

#1061 [1.7] New default make task that generates main and experimental artifacts. (#1041)
  Makefile
Labels: backport
