Repository elastic/ecs, pull requests merged in 2020-04, with the labels that each got.

#763 Add architecture and imphash for PE field set
  CHANGELOG.next.md
  code/go/ecs/pe.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/pe.yml
Labels: 1.6.0

#812 Reverts addition of search field set
  CHANGELOG.next.md
  code/go/ecs/search.go
  docs/field-details.asciidoc
  docs/fields.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/search.yml
Labels: 1.6.0

#827 [DOCS] Removes incorrect `nested` datatype definition
  docs/faq.asciidoc
Labels: 1.5.0, documentation, needs_backport

#830 Backport #827 to 1.5: [DOCS] Removes incorrect `nested` datatype definition (#827)
  docs/faq.asciidoc
Labels: 1.5.0, backport

#762 Implements x509 extended schema
  CHANGELOG.next.md
  code/go/ecs/x509.go
  docs/field-details.asciidoc
  docs/fields.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/x509.yml
Labels: 1.6.0
