Repository elastic/ecs, pull requests merged in 2020-07, with the labels that each got.

#882 schemas/tracing.yml: add span.id
  CHANGELOG.next.md
  code/go/ecs/tracing.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/tracing.yml
Labels: review

#881 Update templates to reference RFC process
  .github/ISSUE_TEMPLATE/schema-changes-additions.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: review

#873 Generate outputs for each individual subset with custom options
  CHANGELOG.next.md
  scripts/generator.py
  scripts/generators/intermediate_files.py
  scripts/schema/loader.py
  scripts/schema/subset_filter.py
  scripts/tests/unit/test_schema_subset_filter.py
Labels: review

#884 Usage improvements
  README.md
  USAGE.md
Labels: documentation

#890 [RFC] Wildcard Data Type
  rfcs/text/0001-wildcard-data-type.md
Labels: RFC

#894 Update solutions reference section
  docs/products-solutions.asciidoc
Labels: documentation

#893 Usage documentation improvements
  USAGE.md
Labels: documentation

#891 [RFC] `service.environment` field
  rfcs/0002-rfc-environment.md
Labels: RFC

#883 [RFC] Object Field
  rfcs/text/0003-object-field.md
Labels: RFC

#879 [RFC] Session Fields
  rfcs/text/0004-session.md
Labels: RFC, review

#888 Add getting started doc
  docs/images/ecs-getting-started-dashboard.png
  docs/index.asciidoc
  docs/using-getting-started.asciidoc
  docs/using.asciidoc
Labels: documentation
