Repository elastic/ecs, pull requests merged in 2020-03, with the labels that each got.

#759 Enhance description of event.outcome field
  CHANGELOG.next.md
  code/go/ecs/event.go
  docs/field-details.asciidoc
  docs/field-values.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: 1.5.0, categorization

#756 Categorization: Add new "iam" category and associated types "admin", "group", "user"
  CHANGELOG.next.md
  docs/field-details.asciidoc
  docs/field-values.asciidoc
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: 1.5.0, categorization

#758 Clarify event.kind definitions re: vulnerabilities
  CHANGELOG.next.md
  code/go/ecs/event.go
  docs/field-details.asciidoc
  docs/field-values.asciidoc
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: 1.5.0, categorization

#760 Add initial stab at mime_type for file objects
  CHANGELOG.next.md
  code/go/ecs/file.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/file.yml
Labels: 1.5.0

#754 Add rule attribution fields
  CHANGELOG.next.md
  code/go/ecs/rule.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/rule.yml
Labels: 1.5.0

#757 Add event.reference field
  CHANGELOG.next.md
  code/go/ecs/event.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/event.yml
Labels: 1.5.0

#761 Add network category and related types
  CHANGELOG.next.md
  docs/field-details.asciidoc
  docs/field-values.asciidoc
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: 1.5.0, categorization

#772 Set the 1.5.0 release version in 1.5 branch
  code/go/ecs/version.go
  docs/fields.asciidoc
  docs/index.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  version
Labels: 1.5.0

#773 Cut ECS 1.5.0 changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: 1.5.0

#729 Adds a search field set to represent search events
  CHANGELOG.next.md
  code/go/ecs/search.go
  docs/field-details.asciidoc
  docs/fields.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/search.yml
Labels: 1.6.0, enhancement

#784 Improve nested fields documentation
  docs/field-details.asciidoc
  scripts/generators/asciidoc_fields.py
Labels: documentation, review

#790 registry.data.strings field missing array definition.
  CHANGELOG.next.md
  docs/field-details.asciidoc
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/registry.yml
Labels: 1.6.0

#802 Add `log.file.path` to capture the log file path, following Filebeat convention.
  CHANGELOG.next.md
  code/go/ecs/log.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/log.yml
Labels: 1.6.0

#801 Clarify the `user.id` definition, the field should contain a single ID.
  CHANGELOG.next.md
  code/go/ecs/user.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/user.yml
Labels: 1.6.0

#798 Missing changelog for #784
  CHANGELOG.next.md
Labels: 1.6.0, needs_backport

#804 Remove misleading wording about multiple IPs in src/dst or cli/srv
  CHANGELOG.next.md
  code/go/ecs/client.go
  code/go/ecs/destination.go
  code/go/ecs/server.go
  code/go/ecs/source.go
  docs/field-details.asciidoc
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/client.yml
  schemas/destination.yml
  schemas/server.yml
  schemas/source.yml
Labels: 1.6.0
