Repository elastic/ecs, pull requests merged in 2020-12, with the labels that each got.

#1157 Correct the email RFC number, which was already in use
  rfcs/text/0010-email.md
Labels: RFC

#1028 [RFC] Add host metric fields to ECS (stage 2)
  rfcs/text/0005-host-metric-fields.md
  rfcs/text/0005/ec2.json
  rfcs/text/0005/host.yml
Labels: 1.8.0, RFC

#1162 Add notice to the tracing field set, about not nesting field names.
  CHANGELOG.next.md
  code/go/ecs/tracing.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_nested.yml
  schemas/tracing.yml
Labels: 1.7, needs_backport

#1164 Tracing fields should be at top level in Beats artifact
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  generated/beats/fields.ecs.yml
  scripts/generators/beats.py
Labels: 1.7.0, 1.x, bug, needs_backport

#1165 [1.x] Tracing fields should be at the root
  CHANGELOG.next.md
  code/go/ecs/tracing.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_nested.yml
  schemas/tracing.yml
  scripts/generators/beats.py
Labels: backport

#1166 [1.7] Tracing fields should be at the root
  CHANGELOG.next.md
  code/go/ecs/tracing.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_nested.yml
  schemas/tracing.yml
  scripts/generators/beats.py
Labels: backport

#1131 Usage of brackets for a URL containing IPv6 address
  CHANGELOG.next.md
  code/go/ecs/url.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/url.yml
Labels: 1.x, needs_backport, ready

#1168 [1.x] Usage of brackets for a URL containing IPv6 address (#1131)
  CHANGELOG.next.md
  code/go/ecs/url.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/url.yml
Labels: backport

#1014 [RFC] SIP Fields
  rfcs/text/0008-sip-fields.md
  rfcs/text/0008/Sip-via-ordering-example.txt
Labels: 1.8.0, RFC

#1171 6.x index template data type fallback
  CHANGELOG.next.md
  scripts/generators/es_template.py
  scripts/tests/test_es_template.py
Labels: 1.8.0, 1.x, needs_backport

#1172 [1.x] 6.x index template data type fallback (#1171)
  CHANGELOG.next.md
  scripts/generators/es_template.py
  scripts/tests/test_es_template.py
Labels: backport

#1066 Changes related to merging RFC 0007 at stage 3
  CHANGELOG.next.md
  docs/field-details.asciidoc
  docs/usage/user.asciidoc
  experimental/generated/ecs/ecs_nested.yml
  experimental/schemas/user.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  rfcs/text/0007-multiple-users.md
  schemas/user.yml
Labels: 1.8.0, 1.x, needs_backport, ready

#1175 [1.x] Apply RFC 0007 stage 3 changes - multi-user (#1066)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  docs/usage/user.asciidoc
  experimental/generated/ecs/ecs_nested.yml
  experimental/schemas/user.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  schemas/user.yml
Labels: backport

#1176 Handle `error.stack_trace` case for ES 6.x template
  CHANGELOG.next.md
  scripts/generators/es_template.py
Labels: 1.8.0, 1.x, needs_backport

#1177 [1.x] Handle `error.stack_trace` case for ES 6.x template (#1176)
  CHANGELOG.next.md
  scripts/generators/es_template.py
Labels: backport

#1070 [RFC] Service Environment Field - stage 1
  rfcs/text/0002-rfc-environment.md
Labels: 1.9.0, RFC

#1186 Move _meta section back inside mappings, in legacy templates.
  CHANGELOG.next.md
  experimental/generated/elasticsearch/7/template.json
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/agent.json
  generated/elasticsearch/component/client.json
  generated/elasticsearch/component/destination.json
  generated/elasticsearch/component/dll.json
  generated/elasticsearch/component/dns.json
  generated/elasticsearch/component/error.json
  generated/elasticsearch/component/file.json
  generated/elasticsearch/component/host.json
  generated/elasticsearch/component/http.json
  generated/elasticsearch/component/log.json
  generated/elasticsearch/component/observer.json
  generated/elasticsearch/component/organization.json
  generated/elasticsearch/component/process.json
  generated/elasticsearch/component/registry.json
  generated/elasticsearch/component/server.json
  generated/elasticsearch/component/source.json
  generated/elasticsearch/component/tls.json
  generated/elasticsearch/component/url.json
  generated/elasticsearch/component/user.json
  generated/elasticsearch/component/user_agent.json
  scripts/generators/es_template.py
Labels: 1.7, needs_backport

#1187 [1.x] Move _meta section back inside mappings, in legacy templates. (#1186)
  CHANGELOG.next.md
  experimental/generated/elasticsearch/7/template.json
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  scripts/generators/es_template.py
Labels: backport

#1184 [1.x] Apply the RFC 0005 stage 2 (host metrics) changes in the experimental artifacts (#1159)
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/host.json
  experimental/schemas/host.yml
Labels: backport

#1191 Conditional handling in es_template.template_settings
  scripts/generators/es_template.py
Labels: 1.8.0, 1.x, needs_backport

#1192 [1.x] Conditional handling in es_template.template_settings (#1191)
  scripts/generators/es_template.py
Labels: backport

#1193 [1.7] Conditional handling in es_template.template_settings (#1191)
  scripts/generators/es_template.py
Labels: backport

#1189 Artifacts docs page
  CHANGELOG.next.md
  docs/additional.asciidoc
  docs/artifacts.asciidoc
  docs/index.asciidoc
  docs/using-conventions.asciidoc
Labels: 1.8.0, 1.x, documentation, needs_backport

#1195 [1.x] Artifacts docs page (#1189)
  CHANGELOG.next.md
  docs/additional.asciidoc
  docs/artifacts.asciidoc
  docs/index.asciidoc
  docs/using-conventions.asciidoc
Labels: backport

#1067 Remove beta warning label from categorization fields docs
  CHANGELOG.next.md
  docs/field-values.asciidoc
  scripts/templates/field_values.j2
Labels: 1.8.0, 1.x, documentation, needs_backport, ready

#1196 [1.x] Remove beta warning label from categorization fields docs (#1067)
  CHANGELOG.next.md
  docs/field-values.asciidoc
  scripts/templates/field_values.j2
Labels: backport

#1181 Correct wording of `event.reference` description
  CHANGELOG.next.md
  code/go/ecs/event.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: 1.8.0, 1.x, needs_backport

#1197 [1.x] Correct wording of `event.reference` description (#1181)
  CHANGELOG.next.md
  code/go/ecs/event.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: backport

#1201 [1.x] Cut 1.8 FF changelog.next.md #1199
  CHANGELOG.next.md
Labels: forward_port

#1202 [master] Cut 1.8 FF changelog.next.md (#1199)
  CHANGELOG.next.md
Labels: forward_port
