Repository elastic/ecs, pull requests merged in 2021-02, with the labels that each got.

#1240 [RFC] Service Environment Field - Update to align with new proposal stages
  rfcs/text/0002-rfc-environment.md
Labels: RFC

#1250 Add scaled_float type to go generator
  CHANGELOG.next.md
  scripts/cmd/gocodegen/gocodegen.go
Labels: 1.8.0, 1.x, bug, needs_backport

#1251 [1.x] Add scaled_float type to go generator (#1250)
  CHANGELOG.next.md
  scripts/cmd/gocodegen/gocodegen.go
Labels: backport

#1252 [1.8] Add scaled_float type to go generator (#1250)
  CHANGELOG.next.md
  scripts/cmd/gocodegen/gocodegen.go
Labels: backport

#1253 Start of network headers RFC
  rfcs/text/0013-network-headers.md
Labels: RFC

#1071 Extend file.pe Fieldset
  rfcs/text/0014-extend-file-pe.md
  rfcs/text/0014/pe.yml
Labels: 1.9.0, RFC

#1242 Add categorization fields usage docs
  docs/field-values-usage.asciidoc
  docs/field-values.asciidoc
  scripts/templates/field_values.j2
Labels: 1.9.0, 1.x, documentation, needs_backport

#1257 [1.x] Add categorization fields usage docs (#1242)
  docs/field-values-usage.asciidoc
  docs/field-values.asciidoc
  scripts/templates/field_values.j2
Labels: backport

#1229 add time_zone, postal_code, and continent_code
  CHANGELOG.next.md
  code/go/ecs/geo.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/client.json
  experimental/generated/elasticsearch/component/destination.json
  experimental/generated/elasticsearch/component/host.json
  experimental/generated/elasticsearch/component/observer.json
  experimental/generated/elasticsearch/component/server.json
  experimental/generated/elasticsearch/component/source.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/client.json
  generated/elasticsearch/component/destination.json
  generated/elasticsearch/component/host.json
  generated/elasticsearch/component/observer.json
  generated/elasticsearch/component/server.json
  generated/elasticsearch/component/source.json
  schemas/geo.yml
Labels: 1.9.0, 1.x, needs_backport, ready

#1258 [1.x] add time_zone, postal_code, and continent_code (#1229)
  CHANGELOG.next.md
  code/go/ecs/geo.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/client.json
  experimental/generated/elasticsearch/component/destination.json
  experimental/generated/elasticsearch/component/host.json
  experimental/generated/elasticsearch/component/observer.json
  experimental/generated/elasticsearch/component/server.json
  experimental/generated/elasticsearch/component/source.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/client.json
  generated/elasticsearch/component/destination.json
  generated/elasticsearch/component/host.json
  generated/elasticsearch/component/observer.json
  generated/elasticsearch/component/server.json
  generated/elasticsearch/component/source.json
  schemas/geo.yml
Labels: backport

#1077 File.elf create
  rfcs/text/0015-create-file-elf.md
  rfcs/text/0015/docs/usage/elf.asciidoc
  rfcs/text/0015/elf.yml
Labels: RFC

#456 Specify MAC address format like this example 00-00-5E-00-53-23
  CHANGELOG.next.md
  code/go/ecs/client.go
  code/go/ecs/destination.go
  code/go/ecs/host.go
  code/go/ecs/observer.go
  code/go/ecs/server.go
  code/go/ecs/source.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/client.yml
  schemas/destination.yml
  schemas/host.yml
  schemas/observer.yml
  schemas/server.yml
  schemas/source.yml
Labels: 1.9.0, 1.x, needs_backport

#1260 [1.x] Specify MAC address format (#456)
  CHANGELOG.next.md
  code/go/ecs/client.go
  code/go/ecs/destination.go
  code/go/ecs/host.go
  code/go/ecs/observer.go
  code/go/ecs/server.go
  code/go/ecs/source.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/client.yml
  schemas/destination.yml
  schemas/host.yml
  schemas/observer.yml
  schemas/server.yml
  schemas/source.yml
Labels: backport

#1262 Cut 1.8 changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: 1.8.0

#1265 [1.x] Cut 1.8 changelog #1262
  CHANGELOG.md
  CHANGELOG.next.md
Labels: 1.x, forward_port

#1266 [master] Cut 1.8 changelog #1262
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port

#1248 Add additional host fields
  CHANGELOG.next.md
  code/go/ecs/host.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/schemas/host.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/host.json
  schemas/host.yml
Labels: 1.9.0, 1.x, needs_backport

#1267 [1.x] Add additional host fields (#1248)
  CHANGELOG.next.md
  code/go/ecs/host.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/schemas/host.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/host.json
  schemas/host.yml
Labels: backport

#1256 Stage 1 changes for RFC 0014 - extend pe fields
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/dll.json
  experimental/generated/elasticsearch/component/file.json
  experimental/generated/elasticsearch/component/process.json
  experimental/schemas/pe.yml
Labels: 1.9.0, 1.x, needs_backport

#1270 [1.x] Stage 1 changes for RFC 0014 - extend pe fields (#1256)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/dll.json
  experimental/generated/elasticsearch/component/file.json
  experimental/generated/elasticsearch/component/process.json
  experimental/schemas/pe.yml
Labels: backport

#1239 [RFC] Multiple Users - Update to align with new proposal stages
  rfcs/text/0007-multiple-users.md
Labels: RFC

#1269 Add 2 fields to code_signature
  CHANGELOG.next.md
  code/go/ecs/code_signature.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/dll.json
  experimental/generated/elasticsearch/component/file.json
  experimental/generated/elasticsearch/component/process.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/dll.json
  generated/elasticsearch/component/file.json
  generated/elasticsearch/component/process.json
  schemas/code_signature.yml
Labels: 1.x, needs_backport

#1272 [1.x] Add 2 fields to code_signature (#1269)
  CHANGELOG.next.md
  code/go/ecs/code_signature.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/dll.json
  experimental/generated/elasticsearch/component/file.json
  experimental/generated/elasticsearch/component/process.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/dll.json
  generated/elasticsearch/component/file.json
  generated/elasticsearch/component/process.json
  schemas/code_signature.yml
Labels: backport

#1271 Stage 3 changes for RFC 0007 - remove beta attribute
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_nested.yml
  schemas/user.yml
Labels: 1.9.0, 1.x, needs_backport

#1273 [1.x] Stage 3 changes for RFC 0007 - remove beta attribute (#1271)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_nested.yml
  schemas/user.yml
Labels: backport

#1268 Stage 1 experimental changes for RFC 0008 - threat.indicator fields
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/threat.json
  experimental/schemas/as.yml
  experimental/schemas/file.yml
  experimental/schemas/geo.yml
  experimental/schemas/hash.yml
  experimental/schemas/pe.yml
  experimental/schemas/registry.yml
  experimental/schemas/threat.yml
Labels: 1.9.0, 1.x, needs_backport

#1274 [1.x] Stage 1 experimental changes for RFC 0008 - threat.indicator fields (#1268)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/threat.json
  experimental/schemas/as.yml
  experimental/schemas/file.yml
  experimental/schemas/geo.yml
  experimental/schemas/hash.yml
  experimental/schemas/pe.yml
  experimental/schemas/registry.yml
  experimental/schemas/threat.yml
Labels: backport

#1261 Stage 1 changes for RFC 0015 - add elf fieldset
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/file.json
  experimental/generated/elasticsearch/component/process.json
  experimental/schemas/elf.yml
Labels: 1.9.0, 1.x, needs_backport

#1275 [1.x] Stage 1 changes for RFC 0015 - add elf fieldset (#1261)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/file.json
  experimental/generated/elasticsearch/component/process.json
  experimental/schemas/elf.yml
Labels: backport

#1127 [RFC] Threat Intel - Stage 2
  rfcs/text/0008-threat-intel.md
  rfcs/text/0008/as.yml
  rfcs/text/0008/file.yml
  rfcs/text/0008/geo.yml
  rfcs/text/0008/hash.yml
  rfcs/text/0008/pe.yml
  rfcs/text/0008/registry.yml
  rfcs/text/0008/threat.yml
  rfcs/text/0008/url.yml
  rfcs/text/0008/x509.yml
Labels: RFC

#1278 [1.x] Cut 1.9 FF CHANGELOG.next.md (#1277)
  CHANGELOG.next.md
Labels: forward_port
