Repository elastic/ecs, pull requests merged in 2021-04, with the labels that each got.

#1335 [RFC] Extend Threat Fieldset - Stage 1
  rfcs/text/0018-extend-threat-group-software.md
  rfcs/text/0018/threat.yml
Labels: RFC

#1314 [RFC] 0017 Remove log.original stage 1
  rfcs/text/0017-remove-log-original.md
  rfcs/text/0017/event.yml
  rfcs/text/0017/log.yml
Labels: RFC

#1344 Stage 1 experimental changes for RFC 0018 - extend threat fieldset
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/threat.json
  experimental/schemas/threat.yml
Labels: 1.10.0, 1.x, needs_backport

#1348 [1.x] Stage 1 experimental changes for RFC 0018 - extend threat fieldset (#1344)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/threat.json
  experimental/schemas/threat.yml
Labels: backport

#1254 Add nested type support to go code generator
  CHANGELOG.next.md
  scripts/cmd/gocodegen/gocodegen.go
Labels: 1.10.0, 1.x, needs_backport

#1349 [1.x] Add nested type support to go code generator (#1254)
  CHANGELOG.next.md
  scripts/cmd/gocodegen/gocodegen.go
Labels: backport

#1345 Adjustments to the field set "usage" docs
  CHANGELOG.next.md
  docs/field-details.asciidoc
  scripts/templates/field_details.j2
Labels: 1.x, needs_backport

#1350 Remove extra newline from Go code generator
  CHANGELOG.next.md
  scripts/cmd/gocodegen/gocodegen.go
Labels: 1.10.0, 1.x, bug, needs_backport

#1352 [1.x] Remove extra newline from Go code generator (#1350)
  CHANGELOG.next.md
  scripts/cmd/gocodegen/gocodegen.go
Labels: backport

#1353 [1.x] Adjustments to the field set "usage" docs (#1345)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  scripts/templates/field_details.j2
Labels: backport

#1351 Correct data type for `group.ref` and `software.ref` experimental fields
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/threat.json
  experimental/schemas/threat.yml
Labels: 1.10.0, 1.x, needs_backport

#1356 [1.x] Correct data type for `group.ref` and `software.ref` experimental fields (#1351)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/threat.json
  experimental/schemas/threat.yml
Labels: backport

#1326 Stage 2 changes for RFC 0012 - orchestrator fieldset
  CHANGELOG.next.md
  code/go/ecs/orchestrator.go
  docs/field-details.asciidoc
  docs/fields.asciidoc
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/orchestrator.json
  generated/elasticsearch/template.json
  schemas/orchestrator.yml
Labels: 1.10.0, 1.x, needs_backport

#1359 [1.x] Stage 2 changes for RFC 0012 - orchestrator fieldset (#1326)
  CHANGELOG.next.md
  code/go/ecs/orchestrator.go
  docs/field-details.asciidoc
  docs/fields.asciidoc
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/orchestrator.json
  generated/elasticsearch/template.json
  schemas/orchestrator.yml
Labels: backport

#1357 Stage 0 RFC for `rpc` fieldset
  rfcs/text/0019-rpc-fieldset.md
Labels: RFC

#1361 [1.x] Adjust field set usage docs sidebar links (#1354)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  docs/usage/README.md
  docs/usage/user.asciidoc
  scripts/templates/field_details.j2
Labels: backport

#1367 [RFC] Rollback `data_stream` proposal to stage 2
  rfcs/text/0009-data_stream-fields.md
Labels: RFC

#1307 Stage 2 changes for RFC 0009 - data_stream fields
  CHANGELOG.next.md
  code/go/ecs/data_stream.go
  docs/field-details.asciidoc
  docs/fields.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/data_stream.json
  generated/elasticsearch/template.json
  schemas/data_stream.yml
Labels: 1.10.0, 1.x, needs_backport

#1368 [1.x] Stage 2 changes for RFC 0009 - data_stream fields (#1307)
  CHANGELOG.next.md
  code/go/ecs/data_stream.go
  docs/field-details.asciidoc
  docs/fields.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/data_stream.json
  generated/elasticsearch/template.json
  schemas/data_stream.yml
Labels: backport

#1366 Allow custom descriptions for self-nesting reuses
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_nested.yml
  schemas/README.md
  schemas/process.yml
  scripts/schema/cleaner.py
  scripts/schema/finalizer.py
  scripts/templates/field_details.j2
  scripts/tests/unit/test_schema_cleaner.py
  scripts/tests/unit/test_schema_finalizer.py
Labels: 1.x

#1369 [1.x] Allow custom descriptions for self-nesting reuses (#1366)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_nested.yml
  schemas/README.md
  schemas/process.yml
  scripts/schema/cleaner.py
  scripts/schema/finalizer.py
  scripts/templates/field_details.j2
  scripts/tests/unit/test_schema_cleaner.py
  scripts/tests/unit/test_schema_finalizer.py
Labels: backport

#1371 Cut 1.10 FF CHANGELOG.next.md
  CHANGELOG.next.md
Labels: 1.x, needs_forward_port

#1375 [1.x] Cut 1.10 changelog (#1371)
  CHANGELOG.next.md
Labels: forward_port

#1376 [master] Cut 1.10 changelog (#1371)
  CHANGELOG.next.md
Labels: forward_port

#1309 [RFC] Version Type Field Migration - Stage 0
  rfcs/text/0020-version-type-field-migration.md
Labels: RFC

#1382 Provide updated descriptions for `user.*` field reuses
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_nested.yml
  schemas/user.yml
Labels: 1.10.0, 1.x, needs_backport

#1384 [1.x] Provide updated descriptions for `user.*` field reuses (#1382)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_nested.yml
  schemas/user.yml
Labels: backport

#1385 [1.10] Provide updated descriptions for `user.*` field reuses (#1382)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_nested.yml
  schemas/user.yml
Labels: backport
