Repository elastic/ecs, pull requests merged in 2021-06, with the labels that each got.

#1441 [RFC] Add container metric fields - Stage 0
  rfcs/text/0025-container-metric-fields.md
  rfcs/text/0025/container.yml
Labels: RFC

#1428 [RFC] Add new database object / fieldset - Stage 0
  rfcs/text/0026-database-object.md
Labels: RFC

#1445 Cut changelog for 1.10.0
  CHANGELOG.md
  CHANGELOG.next.md
Labels: 1.10.0

#1448 [1.x] changelog entry for 1.10.0 (#1445)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port

#1443 Remove guidance to lowercase `http.request.method`.
  CHANGELOG.next.md
  code/go/ecs/http.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/http.yml
Labels: 8.0.0

#1427 [PROPOSAL] Add Stage X to the RFC process
  rfcs/0000-rfc-template.md
  rfcs/README.md
  stages.html
Labels: RFC

#1452 Improve cloud region and AZ field descriptions
  CHANGELOG.next.md
  code/go/ecs/cloud.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/cloud.yml
Labels: 1.11.0, 1.x, needs_backport

#1453 [1.x] Improve cloud region and AZ field descriptions (#1452)
  CHANGELOG.next.md
  code/go/ecs/cloud.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/cloud.yml
Labels: backport

#1297 [RFC] Continue target process RFC to stage 1
  rfcs/text/0016-target-process.md
Labels: RFC

#1400 [RFC] Threat Enrichment - Stage 1
  rfcs/text/0021-threat-enrichment.md
  rfcs/text/0021/as.yml
  rfcs/text/0021/event.yml
  rfcs/text/0021/file.yml
  rfcs/text/0021/geo.yml
  rfcs/text/0021/hash.yml
  rfcs/text/0021/pe.yml
  rfcs/text/0021/registry.yml
  rfcs/text/0021/threat.yml
  rfcs/text/0021/url.yml
  rfcs/text/0021/x509.yml
Labels: RFC

#1454 Add field event.agent_id_status
  CHANGELOG.next.md
  Makefile
  code/go/ecs/event.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/event.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/event.json
  schemas/event.yml
Labels: 1.11.0, 1.x, needs_backport

#1456 [1.x] Add field event.agent_id_status (#1454)
  CHANGELOG.next.md
  Makefile
  code/go/ecs/event.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/event.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/event.json
  schemas/event.yml
Labels: backport

#1459 Add support for multi-level self-nestings
  CHANGELOG.next.md
  scripts/schema/finalizer.py
  scripts/tests/unit/test_schema_finalizer.py
Labels: 1.11.0, 1.x, needs_backport

#1466 [1.x] Add support for multi-level self-nestings (#1459)
  CHANGELOG.next.md
  scripts/schema/finalizer.py
  scripts/tests/unit/test_schema_finalizer.py
Labels: backport

#1467 Stage 1 changes for RFC 0016 - `process.target` field reuse
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/process.json
  experimental/schemas/process.yml
Labels: 1.11.0, 1.x, needs_backport

#1470 [1.x] Stage 1 changes for RFC 0016 - `process.target` field reuse (#1467)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/process.json
  experimental/schemas/process.yml
Labels: backport

#1293 [RFC] Create Threat Fieldset - Stage 2 Proposal
  rfcs/text/0008-threat-intel.md
  rfcs/text/0008/as.yml
  rfcs/text/0008/file.yml
  rfcs/text/0008/geo.yml
  rfcs/text/0008/hash.yml
  rfcs/text/0008/pe.yml
  rfcs/text/0008/registry.yml
  rfcs/text/0008/threat.yml
  rfcs/text/0008/url.yml
  rfcs/text/0008/x509.yml
Labels: RFC

#1460 [RFC] Threat Enrichment - Stage 2
  rfcs/text/0021-threat-enrichment.md
Labels: RFC

#1472 [DOCS] Swap columns in field reuse table
  CHANGELOG.next.md
  docs/field-details.asciidoc
  scripts/templates/field_details.j2
Labels: 1.11.0, 1.x, needs_backport

#1475 [1.x] [DOCS] Swap columns in field reuse table (#1472)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  scripts/templates/field_details.j2
Labels: backport

#1477 [1.x] [DOCS] Swap `Field Reuse` column headers (#1476)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  scripts/templates/field_details.j2
Labels: backport

#1479 [1.x] [DOCS] Bulleted list of expected nesting locations (#1473)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  scripts/templates/field_details.j2
Labels: backport

#1471 Stage 2 changes for RFC 0008 - threat indicator fields
  CHANGELOG.next.md
  code/go/ecs/threat.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/threat.json
  experimental/schemas/threat.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/threat.json
  schemas/threat.yml
Labels: 1.11.0

#1485 [1.x] Stage 2 changes for RFC 0008 - threat indicator fields (#1471)
  CHANGELOG.next.md
  code/go/ecs/threat.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/threat.json
  experimental/schemas/threat.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/threat.json
  schemas/threat.yml
Labels: backport

#1478 Stage 2 changes for RFC 0021 - Threat enrichments
  CHANGELOG.next.md
  code/go/ecs/threat.go
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/schemas/as.yml
  experimental/schemas/event.yml
  experimental/schemas/file.yml
  experimental/schemas/geo.yml
  experimental/schemas/hash.yml
  experimental/schemas/threat.yml
  experimental/schemas/url.yml
  experimental/schemas/x509.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/threat.json
  schemas/as.yml
  schemas/event.yml
  schemas/file.yml
  schemas/geo.yml
  schemas/hash.yml
  schemas/threat.yml
  schemas/url.yml
  schemas/x509.yml
Labels: 1.11.0, 1.x, needs_backport

#1486 [1.x] Implement Deprecation Notice relating to RFC 0017: Remove log.original (#1469)
  CHANGELOG.next.md
  code/go/ecs/event.go
  code/go/ecs/log.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
  schemas/log.yml
Labels: backport

#1487 [1.x] Stage 2 changes for RFC 0021 - Threat enrichments (#1478)
  CHANGELOG.next.md
  code/go/ecs/threat.go
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/schemas/as.yml
  experimental/schemas/event.yml
  experimental/schemas/file.yml
  experimental/schemas/geo.yml
  experimental/schemas/hash.yml
  experimental/schemas/threat.yml
  experimental/schemas/url.yml
  experimental/schemas/x509.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/threat.json
  schemas/as.yml
  schemas/event.yml
  schemas/file.yml
  schemas/geo.yml
  schemas/hash.yml
  schemas/threat.yml
  schemas/url.yml
  schemas/x509.yml
Labels: backport

#1489 [1.x] Remove `ignore_above` parameter when indexing is disabled on field (#1483)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/event.json
  experimental/generated/elasticsearch/component/log.json
  experimental/generated/elasticsearch/component/threat.json
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/error.json
  generated/elasticsearch/component/event.json
  generated/elasticsearch/component/log.json
  generated/elasticsearch/component/threat.json
  scripts/schema/cleaner.py
  scripts/tests/unit/test_schema_cleaner.py
Labels: backport

#1494 [master] update changelog for FF
  CHANGELOG.next.md
Labels: forward_port

#1495 [1.x] changelog forward port for FF
  CHANGELOG.next.md
Labels: forward_port

#1488 Ensure `doc_values` parameter is passed into Beats field defintions
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  generated/beats/fields.ecs.yml
  scripts/generators/beats.py
  scripts/tests/unit/test_beats_generator.py
Labels: 1.11.0, 1.x, needs_backport

#1498 [1.11] Ensure `doc_values` parameter is passed into Beats field defintions (#1488)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  generated/beats/fields.ecs.yml
  scripts/generators/beats.py
  scripts/tests/unit/test_beats_generator.py
Labels: backport

#1497 [1.x] Ensure `doc_values` parameter is passed into Beats field defintions (#1488)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  generated/beats/fields.ecs.yml
  scripts/generators/beats.py
  scripts/tests/unit/test_beats_generator.py
Labels: backport
