Repository elastic/ecs, pull requests merged in 2021-08, with the labels that each got.

#1540 Stage 3 changes for RFC 0018 - extend `threat.*` field set
  CHANGELOG.next.md
  code/go/ecs/threat.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/threat.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/threat.json
  schemas/threat.yml
Labels: 1.12.0, 1.x, needs_backport

#1545 [1.x] Stage 3 changes for RFC 0018 - extend `threat.*` field set (#1540)
  CHANGELOG.next.md
  code/go/ecs/threat.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/threat.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/threat.json
  schemas/threat.yml
Labels: backport

#1546 Stage 1 changes for RFC 0025 - container metric fields
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/container.json
  experimental/schemas/container.yml
Labels: 1.12.0, 1.x, needs_backport

#1549 [1.x] Stage 1 changes for RFC 0025 - container metric fields (#1546)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/container.json
  experimental/schemas/container.yml
Labels: backport

#1548 Update event.kind allowed value descriptions to clarify usage of "alert" and "signal"
  CHANGELOG.next.md
  docs/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: 1.11.0, 1.x, needs_backport

#1551 [1.11] Update event.kind allowed value descriptions to clarify usage of "alert" and "signal" (#1548)
  CHANGELOG.next.md
  docs/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: backport

#1550 [1.x] Update event.kind allowed value descriptions to clarify usage of "alert" and "signal" (#1548)
  CHANGELOG.next.md
  docs/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: backport

#1544 Add process.end field
  CHANGELOG.next.md
  code/go/ecs/process.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/process.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/process.json
  schemas/process.yml
Labels: 1.12.0, 1.x, needs_backport

#1552 [1.x] Add process.end field (#1544)
  CHANGELOG.next.md
  code/go/ecs/process.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/process.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/process.json
  schemas/process.yml
Labels: backport

#1553 [1.x] New event categorization values to support threat intel use cases (#1510)
  docs/field-details.asciidoc
  docs/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: backport

#1554 [1.11] New event categorization values to support threat intel use cases (#1510)
  docs/field-details.asciidoc
  docs/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: backport

#1557 Add `code_signature.digest_algorithm` and `code_signature.timestamp` fields
  code/go/ecs/code_signature.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/dll.json
  experimental/generated/elasticsearch/component/file.json
  experimental/generated/elasticsearch/component/process.json
  experimental/generated/elasticsearch/component/threat.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/dll.json
  generated/elasticsearch/component/file.json
  generated/elasticsearch/component/process.json
  generated/elasticsearch/component/threat.json
  schemas/code_signature.yml
Labels: needs_backport, 1.x, 1.12.0

#1561 [1.x] Add `code_signature.digest_algorithm` and `code_signature.timestamp` fields (#1557)
  code/go/ecs/code_signature.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/dll.json
  experimental/generated/elasticsearch/component/file.json
  experimental/generated/elasticsearch/component/process.json
  experimental/generated/elasticsearch/component/threat.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/dll.json
  generated/elasticsearch/component/file.json
  generated/elasticsearch/component/process.json
  generated/elasticsearch/component/threat.json
  schemas/code_signature.yml
Labels: backport

#1556 RFC 0022 stage 2 - Remove `process.ppid` field
  rfcs/text/0022-remove-process-ppid.md
Labels: RFC

#1558 Cut 1.11 CHANGELOG
  CHANGELOG.md
  CHANGELOG.next.md
Labels: 1.11.0

#1562 [master] Cut 1.11 changelog (#1558)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port

#1563 [1.x] Cut 1.11 changelog (#1558)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port

#1560 [RFC] `text` to `match_only_text` field type migration - Stage 3
  rfcs/text/0023-match_only_text-data-type.md
Labels: RFC

#1530 [RFC] `wildcard` field migration - stage 3
  rfcs/text/0001-wildcard-data-type.md
Labels: RFC

#1566 Update user name & id docs for clarity
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/user.yml
Labels: needs_backport, 1.x, 1.12.0

#1568 [1.x] Update user name & id docs for clarity (#1566)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/user.yml
Labels: backport

#1219 [RFC] Email - Stage 1 Proposal
  rfcs/text/0010-email.md
  rfcs/text/0010/email.yml
  rfcs/text/0010/event.yml
Labels: RFC

#1569 RFC 0010 Stage 1 - Add `email.*` fields to experimental schema
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/email.json
  experimental/generated/elasticsearch/template.json
  experimental/schemas/email.yml
Labels: needs_backport, 1.x, 1.12.0

#1570 [1.x] RFC 0010 Stage 1 - Add `email.*` fields to experimental schema (#1569)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/email.json
  experimental/generated/elasticsearch/template.json
  experimental/schemas/email.yml
Labels: backport

#1571 [RFC] `match_only_text` stage 2 - additional changes
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/http.json
  experimental/generated/elasticsearch/component/organization.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/http.json
  generated/elasticsearch/component/organization.json
  schemas/http.yml
  schemas/organization.yml
Labels: needs_backport, 1.x, 1.12.0

#1572 [1.x] [RFC] `match_only_text` stage 2 - additional changes (#1571)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/http.json
  experimental/generated/elasticsearch/component/organization.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/http.json
  generated/elasticsearch/component/organization.json
  schemas/http.yml
  schemas/organization.yml
Labels: backport

#1573 Cut 1.12 FF changelog.next
  CHANGELOG.next.md
Labels: needs_forward_port

#1575 [master] Cut 1.12 FF changelog.next section (#1573)
  CHANGELOG.next.md
Labels: forward_port

#1576 [1.x] Cut 1.12 FF changelog.next section (#1573)
  CHANGELOG.next.md
Labels: forward_port

#1579 [1.12] fix breaking changes and their sections now that CHANGELOG.next is pointing to 8.0 (#1577)
  CHANGELOG.next.md
Labels: backport

#1580 RFC 0017 - remove `log.original` field
  CHANGELOG.next.md
  code/go/ecs/log.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/log.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/log.json
  schemas/log.yml
Labels: 8.0.0

#1480 [RFC] Create Threat Fieldset - Stage 3 Proposal
  rfcs/text/0008-threat-intel.md
  rfcs/text/0008/threat.yml
Labels: RFC, Team: ECS

#1567 Remove Go code generator
  .github/workflows/test.yml
  CHANGELOG.next.md
  Makefile
  code/README.md
  code/go/ecs/README.md
  code/go/ecs/agent.go
  code/go/ecs/as.go
  code/go/ecs/base.go
  code/go/ecs/client.go
  code/go/ecs/cloud.go
  code/go/ecs/code_signature.go
  code/go/ecs/container.go
  code/go/ecs/data_stream.go
  code/go/ecs/destination.go
  code/go/ecs/dll.go
  code/go/ecs/dns.go
  code/go/ecs/doc.go
  code/go/ecs/ecs.go
  code/go/ecs/elf.go
  code/go/ecs/error.go
  code/go/ecs/event.go
  code/go/ecs/file.go
  code/go/ecs/geo.go
  code/go/ecs/group.go
  code/go/ecs/hash.go
  code/go/ecs/host.go
  code/go/ecs/http.go
  code/go/ecs/interface.go
  code/go/ecs/log.go
  code/go/ecs/network.go
  code/go/ecs/observer.go
  code/go/ecs/orchestrator.go
  code/go/ecs/organization.go
  code/go/ecs/os.go
  code/go/ecs/package.go
  code/go/ecs/pe.go
  code/go/ecs/process.go
  code/go/ecs/registry.go
  code/go/ecs/related.go
  code/go/ecs/rule.go
  code/go/ecs/server.go
  code/go/ecs/service.go
  code/go/ecs/source.go
  code/go/ecs/threat.go
  code/go/ecs/tls.go
  code/go/ecs/tracing.go
  code/go/ecs/url.go
  code/go/ecs/user.go
  code/go/ecs/user_agent.go
  code/go/ecs/version.go
  code/go/ecs/vlan.go
  code/go/ecs/vulnerability.go
  code/go/ecs/x509.go
  scripts/cmd/gocodegen/gocodegen.go
  scripts/cmd/template/template.go
  scripts/go.mod
  scripts/go.sum
Labels: 8.0.0

#1542 [RFC] Faas fields - stage 1
  rfcs/text/0027-faas-fields.md
  rfcs/text/0027/cloud.yml
  rfcs/text/0027/faas.yml
  rfcs/text/0027/service.yml
Labels: RFC

#1582 RFC 0001 `wildcard` type field migration - stage 3 changes
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/error.yml
  schemas/http.yml
  schemas/process.yml
  schemas/registry.yml
  schemas/url.yml
Labels: 8.0.0

#1584 RFC 0023 `match_only_text` type field migration - stage 3 changes
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/as.yml
  schemas/base.yml
  schemas/error.yml
  schemas/file.yml
  schemas/http.yml
  schemas/organization.yml
  schemas/os.yml
  schemas/process.yml
  schemas/threat.yml
  schemas/url.yml
  schemas/user.yml
  schemas/user_agent.yml
  schemas/vulnerability.yml
Labels: 8.0.0

#1585 Remove remaining golang dependencies
  .github/workflows/test.yml
  CHANGELOG.next.md
  Makefile
Labels: 8.0.0

#1586 RFC 0008 threat indicator fields - stage 3 changes
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/as.yml
  schemas/file.yml
  schemas/geo.yml
  schemas/hash.yml
  schemas/pe.yml
  schemas/registry.yml
  schemas/threat.yml
  schemas/url.yml
  schemas/x509.yml
Labels: 8.0.0

#1588 fix: Prevent failure if no files need to be deleted `find | xargs rm`
  CHANGELOG.next.md
  Makefile
Labels: 1.12.0

#1596 Remove `process.ppid` field
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/process.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/process.json
  schemas/process.yml
Labels: 8.0.0
