Repository elastic/ecs, pull requests merged in 2021-12, with the labels that each got.

#1679 [DOCS] Reorganizing docs directory structure
  docs/additional-info/artifacts.asciidoc
  docs/additional-info/contributing.asciidoc
  docs/additional-info/faq.asciidoc
  docs/additional-info/glossary.asciidoc
  docs/additional-info/index.asciidoc
  docs/fields/field-details.asciidoc
  docs/fields/field-values-usage.asciidoc
  docs/fields/field-values.asciidoc
  docs/fields/fields.asciidoc
  docs/fields/usage/README.md
  docs/fields/usage/cloud.asciidoc
  docs/fields/usage/service.asciidoc
  docs/fields/usage/user.asciidoc
  docs/index.asciidoc
  docs/logstash.asciidoc.disabled
  docs/migrating/converting.asciidoc
  docs/migrating/index.asciidoc
  docs/migrating/products-solutions.asciidoc
  docs/using-ecs/conventions.asciidoc
  docs/using-ecs/custom-fields.asciidoc
  docs/using-ecs/getting-started.asciidoc
  docs/using-ecs/guidelines.asciidoc
  docs/using-ecs/images/ecs-getting-started-dashboard.png
  docs/using-ecs/index.asciidoc
  docs/using-ecs/mapping-network-events.asciidoc
  scripts/generators/asciidoc_fields.py
  scripts/generators/ecs_helpers.py
  scripts/templates/index.j2
Labels: DOCS

#1681 [8.0] [DOCS] Reorganizing docs directory structure (#1679)
  docs/additional-info/artifacts.asciidoc
  docs/additional-info/contributing.asciidoc
  docs/additional-info/faq.asciidoc
  docs/additional-info/glossary.asciidoc
  docs/additional-info/index.asciidoc
  docs/fields/field-details.asciidoc
  docs/fields/field-values-usage.asciidoc
  docs/fields/field-values.asciidoc
  docs/fields/fields.asciidoc
  docs/fields/usage/README.md
  docs/fields/usage/cloud.asciidoc
  docs/fields/usage/service.asciidoc
  docs/fields/usage/user.asciidoc
  docs/index.asciidoc
  docs/logstash.asciidoc.disabled
  docs/migrating/converting.asciidoc
  docs/migrating/index.asciidoc
  docs/migrating/products-solutions.asciidoc
  docs/using-ecs/conventions.asciidoc
  docs/using-ecs/custom-fields.asciidoc
  docs/using-ecs/getting-started.asciidoc
  docs/using-ecs/guidelines.asciidoc
  docs/using-ecs/images/ecs-getting-started-dashboard.png
  docs/using-ecs/index.asciidoc
  docs/using-ecs/mapping-network-events.asciidoc
  scripts/generators/asciidoc_fields.py
  scripts/generators/ecs_helpers.py
  scripts/templates/index.j2
Labels: backport

#1683 [8.0] Add missing changelog entry for #1679
  CHANGELOG.next.md
Labels: backport

#1593 [RFC] Introduce `email` field set - stage 2
  rfcs/text/0010-email.md
  rfcs/text/0010/email.yml
Labels: RFC

#1680 removing es6 support in ecs 8.0
  CHANGELOG.next.md
  generated/elasticsearch/6/template.json
  generated/elasticsearch/README.md
  scripts/generator.py
  scripts/generators/es_template.py
  scripts/tests/test_es_template.py
Labels: needs_backport, 8.0.0, breaking

#1689 [8.0] removing es6 support in ecs 8.0 (#1680)
  CHANGELOG.next.md
  generated/elasticsearch/6/template.json
  generated/elasticsearch/README.md
  scripts/generator.py
  scripts/generators/es_template.py
  scripts/tests/test_es_template.py
Labels: backport

#1690 [8.0] Align input options for --include and --subset arguments (#1519)
  CHANGELOG.next.md
  USAGE.md
  scripts/generators/ecs_helpers.py
  scripts/schema/loader.py
  scripts/tests/test_ecs_helpers.py
  scripts/tests/unit/test_schema_loader.py
Labels: backport

#1688 RFC 0010 `email.*` field set - stage 2 changes
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  docs/fields/field-values.asciidoc
  docs/fields/fields.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/email.json
  experimental/generated/elasticsearch/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/7/template.json
  generated/elasticsearch/template.json
  schemas/email.yml
  schemas/event.yml
  schemas/hash.yml
Labels: 8.1.0

#1695 Creating 8.1 SFF changelog.next section
  CHANGELOG.next.md
Labels: 8.1.0

#1697 [`main`] cutting 8.1 SFF changelog.next section (#1695)
  CHANGELOG.next.md
Labels: forward_port

#1699 Ppid deprecation notice
  code/go/ecs/process.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/process.yml
Labels: 1.12.1

#1705 add component template for email.* field set
  CHANGELOG.next.md
  generated/elasticsearch/component/email.json
Labels: bug, needs_backport, 8.1.0

#1706 [8.1] add component template for email.* field set (#1705)
  CHANGELOG.next.md
  generated/elasticsearch/component/email.json
Labels: backport
