Repository elastic/ecs, pull requests merged in 2021-11, with the labels that each got.

#1645 Improve descriptions for `network.*` fields
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/network.yml
Labels: needs_backport, 8.0.0

#1648 [8.0] Improve descriptions for `network.*` fields (#1645)
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/network.yml
Labels: backport

#1627 Stage one of cgroup RFC
  rfcs/text/0028-cgroups.md
  rfcs/text/0028/cgroups.yml
Labels: RFC

#1653 [Bugfix] Add `flattened` fallback to `object` see issue #1649
  CHANGELOG.next.md
  generated/elasticsearch/6/template.json
  scripts/generators/es_template.py
Labels: needs_backport

#1656 [1.12] [Bugfix] Add `flattened` fallback to `object` see issue #1649 (#1653)
  CHANGELOG.next.md
  generated/elasticsearch/6/template.json
  scripts/schema/oss.py
Labels: backport

#1657 [1.11] [Bugfix] Add `flattened` fallback to `object` see issue #1649 (#1653)
  CHANGELOG.next.md
  generated/elasticsearch/6/template.json
  scripts/schema/oss.py
Labels: backport

#1666 RFC 0016 `process.target.*` - Set to Stage X
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/process.json
  experimental/schemas/process.yml
  rfcs/text/0016-target-process.md
Labels: RFC

#1670 RFC 0016 extend `pe.*` field set - Set to Stage X
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/dll.json
  experimental/generated/elasticsearch/component/file.json
  experimental/generated/elasticsearch/component/process.json
  experimental/generated/elasticsearch/component/threat.json
  experimental/schemas/pe.yml
  rfcs/text/0014-extend-file-pe.md
Labels: RFC

#1673 Expand `[source|destination|client|server].domain` field descriptions
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/client.yml
  schemas/destination.yml
  schemas/server.yml
  schemas/source.yml
Labels: needs_backport, 8.0.0

#1676 [8.0] Expand `[source|destination|client|server].domain` field descriptions (#1673)
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/client.yml
  schemas/destination.yml
  schemas/server.yml
  schemas/source.yml
Labels: backport
