Repository elastic/ecs, pull requests merged in 2021-01, with the labels that each got.

#1145 [RFC] wip: data_stream - stage 2
  rfcs/text/0009-data_stream-fields.md
  rfcs/text/0009/data_stream.yml
Labels: RFC

#982 Merge custom and core multi_fields array
  CHANGELOG.next.md
  scripts/schema/loader.py
  scripts/tests/unit/test_schema_loader.py
Labels: Feature: ECS, enhancement, review

#1213 [1.x] Merge custom and core multi_fields arrays (#982)
  CHANGELOG.next.md
  scripts/schema/loader.py
  scripts/tests/unit/test_schema_loader.py
Labels: backport

#1214 [1.8] Merge custom and core multi_fields arrays (#982)
  CHANGELOG.next.md
  scripts/schema/loader.py
  scripts/tests/unit/test_schema_loader.py
Labels: backport

#1209 Add strawperson (stage 0) Kubernetes RFC
  rfcs/text/0012-orchestrator-field-set.md
Labels: RFC

#1215 Stage 2 changes for RFC 0009 - data_stream fields
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/data_stream.json
  experimental/generated/elasticsearch/template.json
  experimental/schemas/data_stream.yml
Labels: 1.9.0, 1.x, needs_backport

#1222 [1.x] Stage 2 changes for RFC 0009 - data_stream fields (#1215)
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/data_stream.json
  experimental/generated/elasticsearch/template.json
  experimental/schemas/data_stream.yml
Labels: backport

#1223 [1.x] add http.request.id (#1208)
  CHANGELOG.next.md
  code/go/ecs/http.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/http.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/http.json
  schemas/http.yml
Labels: backport

#1224 [1.x] add cloud.service.name (#1204)
  CHANGELOG.next.md
  code/go/ecs/cloud.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/cloud.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/cloud.json
  schemas/cloud.yml
Labels: backport

#1169 Add ssdeep hash
  CHANGELOG.next.md
  code/go/ecs/hash.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/dll.json
  experimental/generated/elasticsearch/component/file.json
  experimental/generated/elasticsearch/component/process.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/dll.json
  generated/elasticsearch/component/file.json
  generated/elasticsearch/component/process.json
  schemas/hash.yml
Labels: 1.9.0, 1.x, enhancement, needs_backport, ready

#1227 [1.x] Add ssdeep hash (#1169)
  CHANGELOG.next.md
  code/go/ecs/hash.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/dll.json
  experimental/generated/elasticsearch/component/file.json
  experimental/generated/elasticsearch/component/process.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/dll.json
  generated/elasticsearch/component/file.json
  generated/elasticsearch/component/process.json
  schemas/hash.yml
Labels: backport

#1182 [RFC] Add host metric fields to ECS (Stage 3)
  rfcs/text/0005-host-metric-fields.md
  rfcs/text/0005/aws-ec2.json
  rfcs/text/0005/azure-compute-vm.json
  rfcs/text/0005/system-cpu.json
  rfcs/text/0005/system-network.json
Labels: RFC

#1194 [PROPOSAL] Remove Stage 4 from RFC process
  rfcs/0000-rfc-template.md
  rfcs/README.md
  stages.html
Labels: 7.12 candidate, Team: ECS

#1245 [1.x] [CI] Switch to GitHub actions (#1236)
  .github/workflows/test.yml
  .travis.yml
Labels: backport

#1246 [1.8] [CI] Switch to GitHub actions (#1236)
  .github/workflows/test.yml
  .travis.yml
Labels: backport

#1237 [RFC] Roll back wildcard migration to stage one
  rfcs/text/0001-wildcard-data-type.md
Labels: RFC
