Repository elastic/ecs, pull requests merged in 2021-05, with the labels that each got.

#1386 [RFC] Stage 0 - Threat Enrichment
  rfcs/text/0021-threat-enrichment.md
Labels: RFC

#1337 [RFC] Remove process.ppid - Stage 0
  rfcs/text/0022-remove-process-ppid.md
Labels: RFC

#1294 [RFC] Create ELF Fieldset - Stage 2 Proposal
  rfcs/text/0015-create-file-elf.md
  rfcs/text/0015/elf.yml
Labels: RFC

#1402 Client port is wrongly documented
  docs/using-mapping-network-events.asciidoc
Labels: 1.10.0, 1.x, DOCS, needs_backport

#1407 [1.x] Client port is wrongly documented (#1402)
  docs/using-mapping-network-events.asciidoc
Labels: forward_port

#1396 [RFC] `match_only_text` type migration - Stage 0
  rfcs/text/0023-match_only_text-data-type.md
Labels: RFC

#1383 RFC-Stage-0: Proposal to add a "ticket" schema / field definition to ECS
  rfcs/0024-ticket-fields.md
Labels: RFC

#1408 Consolidate `Breaking changes` sections in `CHANGELOG.next`
  CHANGELOG.next.md
  CONTRIBUTING.md
Labels: 1.10.0, 1.x, needs_backport

#1412 [1.x] Consolidate `Breaking changes` sections in `CHANGELOG.next` (#1408)
  CHANGELOG.next.md
Labels: backport

#1413 [1.10] Consolidate `Breaking changes` sections in `CHANGELOG.next`
  CHANGELOG.next.md
Labels: backport

#1405 removing use-cases
  CHANGELOG.next.md
  Makefile
  docs/use-cases.asciidoc.disabled
  scripts/helper.py
  scripts/use-cases.py
  use-cases/README.md
  use-cases/apm.md
  use-cases/apm.yml
  use-cases/auditbeat.md
  use-cases/auditbeat.yml
  use-cases/beats.md
  use-cases/beats.yml
  use-cases/filebeat-apache-access.md
  use-cases/filebeat-apache-access.yml
  use-cases/kubernetes.md
  use-cases/kubernetes.yml
  use-cases/logging.md
  use-cases/logging.yml
  use-cases/metricbeat.md
  use-cases/metricbeat.yml
  use-cases/web-logs.md
  use-cases/web-logs.yml
Labels: 8.0.0

#1343 Stage 3 Orchestrator RFC
  rfcs/text/0012-orchestrator-field-set.md
Labels: RFC

#1419 [1.x] Support `match_only_text` in Go code generator (#1418)
  CHANGELOG.next.md
  scripts/cmd/gocodegen/gocodegen.go
Labels: backport

#1417 Stage 3 changes for RFC 0012 - `orchestrator` field set
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_nested.yml
  schemas/orchestrator.yml
Labels: 1.11.0, 1.x, needs_backport

#1421 [1.x] Stage 3 changes for RFC 0012 - `orchestrator` field set (#1417)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_nested.yml
  schemas/orchestrator.yml
Labels: backport

#1410 Stage 2 changes for RFC 0015 - `elf` header
  CHANGELOG.next.md
  code/go/ecs/elf.go
  docs/field-details.asciidoc
  docs/fields.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/threat.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/file.json
  generated/elasticsearch/component/process.json
  schemas/elf.yml
Labels: 1.11.0, 1.x, needs_backport

#1423 [1.x] Stage 2 changes for RFC 0015 - `elf` header (#1410)
  CHANGELOG.next.md
  code/go/ecs/elf.go
  docs/field-details.asciidoc
  docs/fields.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/threat.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/file.json
  generated/elasticsearch/component/process.json
  schemas/elf.yml
Labels: backport

#1422 Add `host.user.*` deprecation notice in field reuse description
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_nested.yml
  schemas/user.yml
Labels: 1.11.0, 1.x, needs_backport

#1425 [1.x] Add `host.user.*` deprecation notice in field reuse description (#1422)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_nested.yml
  schemas/user.yml
Labels: backport

#1395 [RFC] Extend Threat Fieldset - Stage 2 Proposal
  rfcs/text/0018-extend-threat-group-software.md
  rfcs/text/0018/threat.yml
Labels: RFC

#1431 [1.x] [Tooling] Add --exclude flag to Generator to support field removal testing (#1411)
  CHANGELOG.next.md
  USAGE.md
  scripts/generator.py
  scripts/generators/beats.py
  scripts/generators/ecs_helpers.py
  scripts/generators/es_template.py
  scripts/generators/intermediate_files.py
  scripts/schema/cleaner.py
  scripts/schema/exclude_filter.py
  scripts/schema/finalizer.py
  scripts/schema/loader.py
  scripts/schema/subset_filter.py
  scripts/schema/visitor.py
  scripts/tests/unit/test_schema_cleaner.py
  scripts/tests/unit/test_schema_exclude_filter.py
  scripts/tests/unit/test_schema_loader.py
  scripts/tests/unit/test_schema_subset_filter.py
Labels: backport

#1432 [1.10] [Tooling] Add --exclude flag to Generator to support field removal testing (#1411)
  CHANGELOG.next.md
  USAGE.md
  scripts/generator.py
  scripts/generators/beats.py
  scripts/generators/ecs_helpers.py
  scripts/generators/es_template.py
  scripts/generators/intermediate_files.py
  scripts/schema/cleaner.py
  scripts/schema/exclude_filter.py
  scripts/schema/finalizer.py
  scripts/schema/loader.py
  scripts/schema/subset_filter.py
  scripts/schema/visitor.py
  scripts/tests/unit/test_schema_cleaner.py
  scripts/tests/unit/test_schema_exclude_filter.py
  scripts/tests/unit/test_schema_loader.py
  scripts/tests/unit/test_schema_subset_filter.py
Labels: backport

#1433 [1.9] [Tooling] Add --exclude flag to Generator to support field removal testing (#1411)
  CHANGELOG.next.md
  USAGE.md
  scripts/generator.py
  scripts/generators/beats.py
  scripts/generators/ecs_helpers.py
  scripts/generators/es_template.py
  scripts/generators/intermediate_files.py
  scripts/schema/cleaner.py
  scripts/schema/exclude_filter.py
  scripts/schema/finalizer.py
  scripts/schema/loader.py
  scripts/schema/subset_filter.py
  scripts/schema/visitor.py
  scripts/tests/unit/test_schema_cleaner.py
  scripts/tests/unit/test_schema_exclude_filter.py
  scripts/tests/unit/test_schema_loader.py
  scripts/tests/unit/test_schema_subset_filter.py
Labels: backport

#1420 Explicitly include user identifiers in `related.user` field description
  CHANGELOG.next.md
  code/go/ecs/related.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/related.yml
Labels: 1.11.0, 1.x, needs_backport

#1437 [1.x] Explicitly include user identifiers in `related.user` field description (#1420)
  CHANGELOG.next.md
  code/go/ecs/related.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/related.yml
Labels: backport

#1439 Remove deprecated `host.user.*` fields
  CHANGELOG.next.md
  docs/field-details.asciidoc
  docs/usage/user.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/host.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/host.json
  schemas/user.yml
Labels: 8.0.0

#1438 Stage 2 changes for RFC 0018 - extending the `threat.*` field set
  CHANGELOG.next.md
  code/go/ecs/threat.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/schemas/threat.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/threat.json
  schemas/threat.yml
Labels: 1.11.0, 1.x, needs_backport

#1440 [1.x] Stage 2 changes for RFC 0018 - extending the `threat.*` field set (#1438)
  CHANGELOG.next.md
  code/go/ecs/threat.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/schemas/threat.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/threat.json
  schemas/threat.yml
Labels: backport

#1347 [RFC] 0017 Remove log.original stage 2
  rfcs/text/0017-remove-log-original.md
Labels: RFC
