Repository elastic/ecs, pull requests merged in 2021-07, with the labels that each got.

#1504 Threat intelligence RFCs stage 2 addenda
  CHANGELOG.next.md
  code/go/ecs/event.go
  code/go/ecs/threat.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/threat.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/threat.json
  schemas/as.yml
  schemas/event.yml
  schemas/file.yml
  schemas/geo.yml
  schemas/hash.yml
  schemas/pe.yml
  schemas/registry.yml
  schemas/threat.yml
  schemas/url.yml
  schemas/x509.yml
Labels: 1.11.0, 1.x, needs_backport

#1506 [1.x] Threat intelligence RFCs stage 2 addenda (#1504)
  CHANGELOG.next.md
  code/go/ecs/event.go
  code/go/ecs/threat.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/threat.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/threat.json
  schemas/as.yml
  schemas/event.yml
  schemas/file.yml
  schemas/geo.yml
  schemas/hash.yml
  schemas/pe.yml
  schemas/registry.yml
  schemas/threat.yml
  schemas/url.yml
  schemas/x509.yml
Labels: backport

#1507 [1.11] Threat intelligence RFCs stage 2 addenda (#1504)
  CHANGELOG.next.md
  code/go/ecs/event.go
  code/go/ecs/threat.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/threat.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/threat.json
  schemas/as.yml
  schemas/event.yml
  schemas/file.yml
  schemas/geo.yml
  schemas/hash.yml
  schemas/pe.yml
  schemas/registry.yml
  schemas/threat.yml
  schemas/url.yml
  schemas/x509.yml
Labels: backport

#1288 Add file.fork_name to ECS
  CHANGELOG.next.md
  code/go/ecs/file.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/file.json
  experimental/generated/elasticsearch/component/threat.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/file.json
  generated/elasticsearch/component/threat.json
  schemas/file.yml
Labels: 1.12.0, 1.x, needs_backport

#1513 [1.x] Add file.fork_name to ECS (#1288)
  CHANGELOG.next.md
  code/go/ecs/file.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/file.json
  experimental/generated/elasticsearch/component/threat.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/file.json
  generated/elasticsearch/component/threat.json
  schemas/file.yml
Labels: backport

#1511 Present `beta` tooltip for categorization values
  CHANGELOG.next.md
  schemas/README.md
  scripts/templates/field_values.j2
  scripts/tests/test_asciidoc_fields.py
Labels: 1.11.0, 1.x, needs_backport

#1514 [1.x] Present `beta` tooltip for categorization values (#1511)
  CHANGELOG.next.md
  schemas/README.md
  scripts/templates/field_values.j2
  scripts/tests/test_asciidoc_fields.py
Labels: backport

#1515 [1.11] Present `beta` tooltip for categorization values (#1511)
  CHANGELOG.next.md
  schemas/README.md
  scripts/templates/field_values.j2
  scripts/tests/test_asciidoc_fields.py
Labels: backport

#1490 [1.x] Fix Typo in Date (#1463)
  docs/using-getting-started.asciidoc
Labels: backport

#1247 [RFC] Wildcard - stage 2 proposal
  rfcs/text/0001-wildcard-data-type.md
  rfcs/text/0001/agent.yml
  rfcs/text/0001/as.yml
  rfcs/text/0001/client.yml
  rfcs/text/0001/destination.yml
  rfcs/text/0001/dns.yml
  rfcs/text/0001/error.yml
  rfcs/text/0001/file.yml
  rfcs/text/0001/geo.yml
  rfcs/text/0001/host.yml
  rfcs/text/0001/http.yml
  rfcs/text/0001/log.yml
  rfcs/text/0001/organization.yml
  rfcs/text/0001/os.yml
  rfcs/text/0001/pe.yml
  rfcs/text/0001/process.yml
  rfcs/text/0001/registry.yml
  rfcs/text/0001/server.yml
  rfcs/text/0001/source.yml
  rfcs/text/0001/tls.yml
  rfcs/text/0001/url.yml
  rfcs/text/0001/user.yml
  rfcs/text/0001/user_agent.yml
  rfcs/text/0001/x509.yml
Labels: RFC

#1415 [RFC] `match_only_text` type migration - Stage 1
  rfcs/text/0023-match_only_text-data-type.md
  rfcs/text/0023/as.yml
  rfcs/text/0023/base.yml
  rfcs/text/0023/error.yml
  rfcs/text/0023/file.yml
  rfcs/text/0023/os.yml
  rfcs/text/0023/process.yml
  rfcs/text/0023/threat.yml
  rfcs/text/0023/url.yml
  rfcs/text/0023/user.yml
  rfcs/text/0023/user_agent.yml
  rfcs/text/0023/vulnerability.yml
Labels: RFC

#1522 [RFC] `text` to `match_only_text` field type migration - Stage 2
  rfcs/text/0023-match_only_text-data-type.md
Labels: RFC

#1451 [RFC] `version` data type - stage X
  rfcs/text/0020-version-type-field-migration.md
  rfcs/text/0020/ecs.yml
Labels: RFC

#1528 Support multi-field type fallback
  CHANGELOG.next.md
  scripts/generators/es_template.py
  scripts/tests/test_es_template.py
Labels: 1.12.0, 1.x, needs_backport

#1531 [1.x] Support multi-field type fallback (#1528)
  CHANGELOG.next.md
  scripts/generators/es_template.py
  scripts/schema/oss.py
  scripts/tests/test_es_template.py
Labels: backport

#1518 [RFC] FaaS Fields - Stage 0
  rfcs/text/0027-faas-fields.md
Labels: RFC

#1450 [RFC] Remove `process.ppid` - Stage 1
  rfcs/text/0022-remove-process-ppid.md
  rfcs/text/0022/process_exclude.yml
Labels: RFC

#1533 Update `log.origin.file.line` from `integer` to `long`
  CHANGELOG.next.md
  code/go/ecs/log.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/log.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/log.json
  schemas/log.yml
Labels: 8.0.0

#1537 Adding service.address
  CHANGELOG.next.md
  code/go/ecs/service.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/service.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/service.json
  schemas/service.yml
Labels: 1.12.0, needs_backport

#1538 [1.x] Adding service.address (#1537)
  CHANGELOG.next.md
  code/go/ecs/service.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/service.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/service.json
  schemas/service.yml
Labels: backport

#1532 [RFC] `match_only_text` - stage 2 beta changes
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/base.json
  experimental/generated/elasticsearch/component/client.json
  experimental/generated/elasticsearch/component/destination.json
  experimental/generated/elasticsearch/component/error.json
  experimental/generated/elasticsearch/component/file.json
  experimental/generated/elasticsearch/component/host.json
  experimental/generated/elasticsearch/component/observer.json
  experimental/generated/elasticsearch/component/process.json
  experimental/generated/elasticsearch/component/server.json
  experimental/generated/elasticsearch/component/source.json
  experimental/generated/elasticsearch/component/threat.json
  experimental/generated/elasticsearch/component/url.json
  experimental/generated/elasticsearch/component/user.json
  experimental/generated/elasticsearch/component/user_agent.json
  experimental/generated/elasticsearch/component/vulnerability.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/base.json
  generated/elasticsearch/component/client.json
  generated/elasticsearch/component/destination.json
  generated/elasticsearch/component/error.json
  generated/elasticsearch/component/file.json
  generated/elasticsearch/component/host.json
  generated/elasticsearch/component/observer.json
  generated/elasticsearch/component/process.json
  generated/elasticsearch/component/server.json
  generated/elasticsearch/component/source.json
  generated/elasticsearch/component/threat.json
  generated/elasticsearch/component/url.json
  generated/elasticsearch/component/user.json
  generated/elasticsearch/component/user_agent.json
  generated/elasticsearch/component/vulnerability.json
  schemas/as.yml
  schemas/base.yml
  schemas/error.yml
  schemas/file.yml
  schemas/os.yml
  schemas/process.yml
  schemas/threat.yml
  schemas/url.yml
  schemas/user.yml
  schemas/user_agent.yml
  schemas/vulnerability.yml
Labels: 1.12.0, 1.x, needs_backport

#1539 [1.x] [RFC] `match_only_text` - stage 2 beta changes (#1532)
  CHANGELOG.next.md
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/base.json
  experimental/generated/elasticsearch/component/client.json
  experimental/generated/elasticsearch/component/destination.json
  experimental/generated/elasticsearch/component/error.json
  experimental/generated/elasticsearch/component/file.json
  experimental/generated/elasticsearch/component/host.json
  experimental/generated/elasticsearch/component/observer.json
  experimental/generated/elasticsearch/component/process.json
  experimental/generated/elasticsearch/component/server.json
  experimental/generated/elasticsearch/component/source.json
  experimental/generated/elasticsearch/component/threat.json
  experimental/generated/elasticsearch/component/url.json
  experimental/generated/elasticsearch/component/user.json
  experimental/generated/elasticsearch/component/user_agent.json
  experimental/generated/elasticsearch/component/vulnerability.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/base.json
  generated/elasticsearch/component/client.json
  generated/elasticsearch/component/destination.json
  generated/elasticsearch/component/error.json
  generated/elasticsearch/component/file.json
  generated/elasticsearch/component/host.json
  generated/elasticsearch/component/observer.json
  generated/elasticsearch/component/process.json
  generated/elasticsearch/component/server.json
  generated/elasticsearch/component/source.json
  generated/elasticsearch/component/threat.json
  generated/elasticsearch/component/url.json
  generated/elasticsearch/component/user.json
  generated/elasticsearch/component/user_agent.json
  generated/elasticsearch/component/vulnerability.json
  schemas/as.yml
  schemas/base.yml
  schemas/error.yml
  schemas/file.yml
  schemas/os.yml
  schemas/process.yml
  schemas/threat.yml
  schemas/url.yml
  schemas/user.yml
  schemas/user_agent.yml
  schemas/vulnerability.yml
  use-cases/filebeat-apache-access.md
  use-cases/logging.md
  use-cases/metricbeat.md
Labels: backport

#1442 [RFC] Extend Threat Fieldset - Stage 3 Proposal
  rfcs/text/0018-extend-threat-group-software.md
  rfcs/text/0018/threat.yml
Labels: RFC, Team: ECS

#1536 Progressing service.environment RFC to stage 2
  rfcs/text/0002-rfc-environment.md
Labels: RFC

#1541 Stage 2 changes for RFC 0002 - `service.environment`
  CHANGELOG.next.md
  code/go/ecs/service.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/service.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/service.json
  schemas/service.yml
Labels: 1.12.0, 1.x, needs_backport

#1543 [1.x] Stage 2 changes for RFC 0002 - `service.environment` (#1541)
  CHANGELOG.next.md
  code/go/ecs/service.go
  docs/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/7/template.json
  experimental/generated/elasticsearch/component/service.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/6/template.json
  generated/elasticsearch/7/template.json
  generated/elasticsearch/component/service.json
  schemas/service.yml
Labels: backport

#1529 [RFC] Add container metric fields - Stage 1
  rfcs/text/0025-container-metric-fields.md
Labels: RFC
