Repository elastic/ecs, pull requests merged in 2022-09, with the labels that each got.

#2051 Adding `risk.*` as beta
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  docs/fields/fields.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/client.json
  experimental/generated/elasticsearch/composable/component/destination.json
  experimental/generated/elasticsearch/composable/component/server.json
  experimental/generated/elasticsearch/composable/component/source.json
  experimental/generated/elasticsearch/legacy/template.json
  experimental/schemas/subsets/experimental.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/client.json
  generated/elasticsearch/composable/component/destination.json
  generated/elasticsearch/composable/component/host.json
  generated/elasticsearch/composable/component/server.json
  generated/elasticsearch/composable/component/source.json
  generated/elasticsearch/composable/component/user.json
  generated/elasticsearch/legacy/template.json
  schemas/risk.yml
  schemas/subsets/main.yml
Labels: needs_backport, 8.5.0

#2052 [8.5] Adding `risk.*` as beta (#2051)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  docs/fields/fields.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/client.json
  experimental/generated/elasticsearch/composable/component/destination.json
  experimental/generated/elasticsearch/composable/component/server.json
  experimental/generated/elasticsearch/composable/component/source.json
  experimental/generated/elasticsearch/legacy/template.json
  experimental/schemas/subsets/experimental.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/client.json
  generated/elasticsearch/composable/component/destination.json
  generated/elasticsearch/composable/component/host.json
  generated/elasticsearch/composable/component/server.json
  generated/elasticsearch/composable/component/source.json
  generated/elasticsearch/composable/component/user.json
  generated/elasticsearch/legacy/template.json
  schemas/risk.yml
  schemas/subsets/main.yml
Labels: backport

#2050 Add attested user and groups to process
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/process.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/process.json
  generated/elasticsearch/legacy/template.json
  schemas/group.yml
  schemas/subsets/main.yml
  schemas/user.yml
Labels: needs_backport, RFC, 8.5.0

#2054 [8.5] Add attested user and groups to process (#2050)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/process.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/process.json
  generated/elasticsearch/legacy/template.json
  schemas/group.yml
  schemas/subsets/main.yml
  schemas/user.yml
Labels: backport

#2056 Cutting 8.5 changelog for HFF
  CHANGELOG.next.md
Labels: needs_forward_port, 8.5.0

#2029 Add vulnerability to event.category
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  docs/fields/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: 8.6.0

#2058 Refining the addition of the `risk.*` fields locations
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/client.json
  experimental/generated/elasticsearch/composable/component/destination.json
  experimental/generated/elasticsearch/composable/component/server.json
  experimental/generated/elasticsearch/composable/component/source.json
  experimental/generated/elasticsearch/composable/component/user.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/client.json
  generated/elasticsearch/composable/component/destination.json
  generated/elasticsearch/composable/component/server.json
  generated/elasticsearch/composable/component/source.json
  generated/elasticsearch/composable/component/user.json
  generated/elasticsearch/legacy/template.json
  schemas/subsets/main.yml
Labels: bug, needs_backport, 8.5.0

#2067 [8.5] Refining the addition of the `risk.*` fields locations (#2058)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/client.json
  experimental/generated/elasticsearch/composable/component/destination.json
  experimental/generated/elasticsearch/composable/component/server.json
  experimental/generated/elasticsearch/composable/component/source.json
  experimental/generated/elasticsearch/composable/component/user.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/client.json
  generated/elasticsearch/composable/component/destination.json
  generated/elasticsearch/composable/component/server.json
  generated/elasticsearch/composable/component/source.json
  generated/elasticsearch/composable/component/user.json
  generated/elasticsearch/legacy/template.json
  schemas/subsets/main.yml
Labels: backport

#2068 [8.6] Refining the addition of the `risk.*` fields locations (#2058)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/client.json
  experimental/generated/elasticsearch/composable/component/destination.json
  experimental/generated/elasticsearch/composable/component/server.json
  experimental/generated/elasticsearch/composable/component/source.json
  experimental/generated/elasticsearch/composable/component/user.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/client.json
  generated/elasticsearch/composable/component/destination.json
  generated/elasticsearch/composable/component/server.json
  generated/elasticsearch/composable/component/source.json
  generated/elasticsearch/composable/component/user.json
  generated/elasticsearch/legacy/template.json
  schemas/subsets/main.yml
Labels: backport

#2071 cut 8.6 SFF Changelog
  CHANGELOG.next.md
Labels: needs_forward_port
