Repository elastic/ecs, pull requests merged in 2022-08, with the labels that each got.

#2014 Fixes a typo in the client schema
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/client.yml
Labels: needs_backport, 8.5.0

#2020 [8.5] Fixes a typo in the client schema (#2014)
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/client.yml
Labels: backport

#2013 [RFC] Stage 0 - New Fieldset for Device
  rfcs/text/0000-device-fields.md
Labels: RFC

#2021 Correction to new device RFC
  rfcs/text/0034-device-fields.md
Labels: RFC

#2018 fix: fields asciidoc folder needs to be created
  scripts/generators/asciidoc_fields.py
Labels: 8.6.0

#2026 RFC Stage 1: Device fields
  rfcs/text/0034-device-fields.md
  rfcs/text/0034/device.yml
Labels: RFC

#1956 [Stage 0/1] Initial draft for IO fieldset RFC
  rfcs/text/0035-tty-output.md
  rfcs/text/0035/process.yml
Labels: RFC, 8.5.0

#2030 Device fields RFC stage 2 and schema change
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  docs/fields/fields.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/device.json
  experimental/generated/elasticsearch/composable/template.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/device.json
  generated/elasticsearch/composable/template.json
  generated/elasticsearch/legacy/template.json
  rfcs/text/0034-device-fields.md
  schemas/device.yml
  schemas/subsets/main.yml
Labels: RFC, 8.6.0

#2032 Update implementation.asciidoc
  docs/using-ecs/guidelines/implementation.asciidoc
Labels: DOCS

#2035 8.4 changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: needs_forward_port, 8.4.0

#2040 [main] 8.4 changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port

#2039 [8.5] 8.4 changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port

#2036 8.4 release notes
  docs/release-notes/8.4.asciidoc
Labels: documentation, needs_forward_port, 8.4.0

#2041 [8.5] 8.4 release notes (#2036)
  docs/release-notes/8.4.asciidoc
Labels: forward_port

#2042 [main] 8.4 release notes (#2036)
  docs/release-notes/8.4.asciidoc
Labels: forward_port

#2038 Changed type of process.env_vars to show shadowing
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/process.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/process.json
  generated/elasticsearch/legacy/template.json
  schemas/process.yml
Labels: needs_backport, 8.5.0

#2043 [8.5] Changed type of process.env_vars to show shadowing (#2038)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/process.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/process.json
  generated/elasticsearch/legacy/template.json
  schemas/process.yml
Labels: backport

#2031 [RFC Stage-2] Process IO events
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/process.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/process.json
  generated/elasticsearch/legacy/template.json
  rfcs/text/0035-tty-output.md
  rfcs/text/0035/process.yml
  schemas/process.yml
Labels: needs_backport, RFC, 8.5.0

#2045 [8.5] [RFC Stage-2] Process IO events (#2031)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/process.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/process.json
  generated/elasticsearch/legacy/template.json
  rfcs/text/0035-tty-output.md
  rfcs/text/0035/process.yml
  schemas/process.yml
Labels: backport
