Repository elastic/ecs, pull requests merged in 2022-05, with the labels that each got.

#1896 [8.3] Add orchestrator (resource.parent.type and resource.ip) and container (image.hash.all) fields (#1889)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/container.json
  experimental/generated/elasticsearch/composable/component/orchestrator.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/container.json
  generated/elasticsearch/composable/component/orchestrator.json
  generated/elasticsearch/legacy/template.json
  schemas/container.yml
  schemas/orchestrator.yml
Labels: backport

#1893 8.2 release changelog entry
  CHANGELOG.md
  CHANGELOG.next.md
Labels: needs_forward_port, 8.2.0

#1898 [8.3] 8.2 release changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port

#1899 [main] 8.2 release changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port

#1895 [Docs] Updated Release Notes docs for 8.2
  docs/release-notes/8.2.asciidoc
Labels: needs_forward_port, DOCS, 8.2.0

#1901 [main] [Docs] Updated Release Notes docs for 8.2 (#1895)
  docs/release-notes/8.2.asciidoc
Labels: forward_port

#1900 [8.3] [Docs] Updated Release Notes docs for 8.2 (#1895)
  docs/release-notes/8.2.asciidoc
Labels: forward_port

#1771 Add type hints to schema modules
  CHANGELOG.next.md
  scripts/_types/__init__.py
  scripts/_types/schema_fields.py
  scripts/generator.py
  scripts/generators/ecs_helpers.py
  scripts/generators/intermediate_files.py
  scripts/schema/cleaner.py
  scripts/schema/exclude_filter.py
  scripts/schema/loader.py
  scripts/schema/subset_filter.py
  scripts/schema/visitor.py
Labels: needs_backport, 8.3.0

#1904 [8.3] Add type hints to schema modules (#1771)
  CHANGELOG.next.md
  scripts/_types/__init__.py
  scripts/_types/schema_fields.py
  scripts/generator.py
  scripts/generators/ecs_helpers.py
  scripts/generators/intermediate_files.py
  scripts/schema/cleaner.py
  scripts/schema/exclude_filter.py
  scripts/schema/loader.py
  scripts/schema/subset_filter.py
  scripts/schema/visitor.py
Labels: backport

#1910 All date examples are quoted
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/threat.yml
  schemas/x509.yml
Labels: needs_backport, 8.3.0

#1911 [8.3] All date examples are quoted
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/threat.yml
  schemas/x509.yml
Labels: backport

#1877 [RFC] Proposal to define ECS-compliance - Stage 2
  rfcs/text/0032-definition-of-ecs-compliance.md
Labels: RFC

#1909 Introduce "docs_only" attribute for subsets
  CHANGELOG.next.md
  USAGE.md
  scripts/generator.py
  scripts/generators/asciidoc_fields.py
  scripts/schema/subset_filter.py
  scripts/tests/test_asciidoc_fields.py
  scripts/tests/unit/test_schema_subset_filter.py
Labels: needs_backport, 8.2.0

#1913 [8.2] Add type hints to schema modules (#1771)
  CHANGELOG.next.md
  scripts/_types/__init__.py
  scripts/_types/schema_fields.py
  scripts/generator.py
  scripts/generators/ecs_helpers.py
  scripts/generators/intermediate_files.py
  scripts/schema/cleaner.py
  scripts/schema/exclude_filter.py
  scripts/schema/loader.py
  scripts/schema/subset_filter.py
  scripts/schema/visitor.py
Labels: backport

#1912 [8.3] Introduce "docs_only" attribute for subsets (#1909)
  CHANGELOG.next.md
  USAGE.md
  scripts/generator.py
  scripts/generators/asciidoc_fields.py
  scripts/schema/subset_filter.py
  scripts/tests/test_asciidoc_fields.py
  scripts/tests/unit/test_schema_subset_filter.py
Labels: backport

#1914 [8.2] Introduce "docs_only" attribute for subsets (#1909)
  CHANGELOG.next.md
  USAGE.md
  scripts/generator.py
  scripts/generators/asciidoc_fields.py
  scripts/schema/subset_filter.py
  scripts/tests/test_asciidoc_fields.py
  scripts/tests/unit/test_schema_subset_filter.py
Labels: backport

#1919 Remove unnecessary guidance from `agent.name` description
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/agent.yml
Labels: needs_backport, 8.2.1

#1922 `related.ip` example should be an array
  docs/using-ecs/guidelines/implementation.asciidoc
Labels: needs_backport, 8.2.1

#1923 [8.3] `related.ip` example should be an array (#1922)
  docs/using-ecs/guidelines/implementation.asciidoc
Labels: backport

#1924 [8.2] `related.ip` example should be an array (#1922)
  docs/using-ecs/guidelines/implementation.asciidoc
Labels: backport

#1906 Re-adding missing process fields
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/process.yml
  schemas/subsets/main.yml
Labels: needs_backport, 8.2.1

#1929 [8.3] Re-adding missing process fields (#1906)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/process.yml
  schemas/subsets/main.yml
Labels: backport

#1930 [8.2] Re-adding missing process fields (#1906)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/process.yml
  schemas/subsets/main.yml
Labels: backport

#1935 [8.3] Container metrics GA (#1927)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  rfcs/text/0025-container-metric-fields.md
  schemas/container.yml
Labels: backport

#1933 Add release notes section for 8.2.1
  docs/release-notes/8.2.1.asciidoc
  docs/release-notes/index.asciidoc
Labels: needs_forward_port, DOCS, 8.2.1

#1932 Changelog cleanup 8.2.1
  CHANGELOG.md
  CHANGELOG.next.md
Labels: needs_forward_port, 8.2.1

#1936 [8.3] Changelog cleanup 8.2.1 (#1932)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port

#1938 8.3 HFF changelog
  CHANGELOG.next.md
Labels: needs_forward_port, 8.3.0

#1940 Adding empty 8.4 release notes section
  docs/release-notes/8.4.asciidoc
  docs/release-notes/index.asciidoc
Labels: needs_backport, 8.4.0

#1943 [8.4] cutting 8.3 HFF changelog (#1938)
  CHANGELOG.next.md
Labels: forward_port

#1941 8.4 SFF changelog
  CHANGELOG.next.md
Labels: needs_forward_port, 8.4.0

#1945 [8.4] adding 8.4 release notes section (#1940)
  docs/release-notes/8.4.asciidoc
  docs/release-notes/index.asciidoc
Labels: backport

#1944 [main] cutting 8.3 HFF changelog (#1938)
  CHANGELOG.next.md
Labels: forward_port

#1946 [main] 8.4 SFF changelog (#1941)
  CHANGELOG.next.md
Labels: forward_port
