Repository elastic/ecs, pull requests merged in 2022-06, with the labels that each got.

#1950 Add type annotations to `scripts.generator` modules
  CHANGELOG.next.md
  scripts/generators/beats.py
  scripts/generators/csv_generator.py
  scripts/generators/es_template.py
  scripts/generators/intermediate_files.py
  scripts/schema/subset_filter.py
  scripts/tests/test_es_template.py
  scripts/tests/unit/test_csv_generator.py
Labels: needs_backport, 8.4.0

#1960 [8.4] Add type annotations to `scripts.generator` modules (#1950)
  CHANGELOG.next.md
  scripts/generators/beats.py
  scripts/generators/csv_generator.py
  scripts/generators/es_template.py
  scripts/generators/intermediate_files.py
  scripts/schema/subset_filter.py
  scripts/tests/test_es_template.py
  scripts/tests/unit/test_csv_generator.py
Labels: backport

#1952 `expected_values` in field definitions
  USAGE.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/README.md
  schemas/x509.yml
  scripts/schema/cleaner.py
  scripts/templates/field_details.j2
  scripts/tests/unit/test_schema_cleaner.py
Labels: needs_backport, 8.4.0

#1961 [8.4] `expected_values` in field definitions (#1952)
  USAGE.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/README.md
  schemas/x509.yml
  scripts/schema/cleaner.py
  scripts/templates/field_details.j2
  scripts/tests/unit/test_schema_cleaner.py
Labels: backport

#1962 Define initial set of field `expected_values`
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/dns.yml
  schemas/faas.yml
  schemas/network.yml
  schemas/os.yml
  schemas/threat.yml
Labels: needs_backport, 8.4.0

#1969 [8.4] finalizing changelog for 8.3 release (#1966)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: backport

#1967 Release notes 8.3
  docs/release-notes/8.3.asciidoc
Labels: needs_backport, 8.3.0

#1973 [8.3] Release notes 8.3 (#1967)
  docs/release-notes/8.3.asciidoc
Labels: backport

#1972 [8.4] Release notes 8.3 (#1967)
  docs/release-notes/8.3.asciidoc
Labels: backport

#1974 [main] 8.3 changelog fix
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port

#1976 Deprecate service.node.role
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/service.yml
Labels: needs_forward_port, 8.3.1

#1977 [main] Deprecate service.node.role
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/service.yml
Labels: forward_port

#1978 [8.4] Deprecate service.node.role
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/service.yml
Labels: forward_port
