Repository elastic/ecs, pull requests merged in 2022-02, with the labels that each got.

#1684 [RFC] Stage 1 - Linux event model
  rfcs/text/0030-linux-event-model.md
  rfcs/text/0030/file.yml
  rfcs/text/0030/file_description.yml
  rfcs/text/0030/group.yml
  rfcs/text/0030/host.yml
  rfcs/text/0030/process.yml
  rfcs/text/0030/source.yml
  rfcs/text/0030/user.yml
Labels: RFC

#1748 8.1 HFF changelog
  CHANGELOG.next.md
Labels: 8.1.0

#1753 Forward-port cutting 8.2 SFF changelog (#1750)
  CHANGELOG.next.md
Labels: forward_port

#1752 Forward-port 8.1 HFF Changelog
  CHANGELOG.next.md
Labels: forward_port

#1755 Include abbr in `FaaS` field set description
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_nested.yml
  schemas/faas.yml
Labels: needs_backport, 8.0.0

#1756 [8.2] Include abbr in `FaaS` field set description (#1755)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_nested.yml
  schemas/faas.yml
Labels: backport

#1757 [8.1] Include abbr in `FaaS` field set description (#1755)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_nested.yml
  schemas/faas.yml
Labels: backport

#1758 [8.0] Include abbr in `FaaS` field set description (#1755)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_nested.yml
  schemas/faas.yml
Labels: backport

#1737 Adding support in for custom analyzers for text and overriding the default template settings for index templates
  CHANGELOG.next.md
  USAGE.md
  scripts/generator.py
  scripts/generators/es_template.py
  scripts/tests/test_es_template.py
  usage-example/README.md
  usage-example/fields/template-settings-legacy.json
  usage-example/fields/template-settings.json
Labels: needs_backport, 8.0.0

#1759 [8.2] Adding support in for custom analyzers for text and overriding the default template settings for index templates (#1737)
  CHANGELOG.next.md
  USAGE.md
  scripts/generator.py
  scripts/generators/es_template.py
  scripts/tests/test_es_template.py
  usage-example/README.md
  usage-example/fields/template-settings-legacy.json
  usage-example/fields/template-settings.json
Labels: backport

#1760 [8.1] Adding support in for custom analyzers for text and overriding the default template settings for index templates (#1737)
  CHANGELOG.next.md
  USAGE.md
  experimental/generated/elasticsearch/composable/template.json
  generated/elasticsearch/composable/template.json
  scripts/generator.py
  scripts/generators/es_template.py
  scripts/tests/test_es_template.py
  usage-example/README.md
  usage-example/fields/template-settings-legacy.json
  usage-example/fields/template-settings.json
Labels: backport

#1761 [8.0] Adding support in for custom analyzers for text and overriding the default template settings for index templates (#1737)
  CHANGELOG.next.md
  USAGE.md
  scripts/generator.py
  scripts/generators/es_template.py
  scripts/tests/test_es_template.py
  usage-example/README.md
  usage-example/fields/template-settings-legacy.json
  usage-example/fields/template-settings.json
Labels: backport

#1762 Restructure `usage-examples` ES generated artifacts
  CHANGELOG.next.md
  usage-example/README.md
  usage-example/generated/beats/fields.ecs.yml
  usage-example/generated/csv/fields.csv
  usage-example/generated/ecs/ecs_flat.yml
  usage-example/generated/ecs/ecs_nested.yml
  usage-example/generated/ecs/subset/web_logs/ecs_flat.yml
  usage-example/generated/ecs/subset/web_logs/ecs_nested.yml
  usage-example/generated/elasticsearch/6/template.json
  usage-example/generated/elasticsearch/composable/component/acme.json
  usage-example/generated/elasticsearch/composable/component/agent.json
  usage-example/generated/elasticsearch/composable/component/base.json
  usage-example/generated/elasticsearch/composable/component/client.json
  usage-example/generated/elasticsearch/composable/component/destination.json
  usage-example/generated/elasticsearch/composable/component/ecs.json
  usage-example/generated/elasticsearch/composable/component/event.json
  usage-example/generated/elasticsearch/composable/component/http.json
  usage-example/generated/elasticsearch/composable/component/network.json
  usage-example/generated/elasticsearch/composable/component/related.json
  usage-example/generated/elasticsearch/composable/component/server.json
  usage-example/generated/elasticsearch/composable/component/source.json
  usage-example/generated/elasticsearch/composable/component/url.json
  usage-example/generated/elasticsearch/composable/component/user.json
  usage-example/generated/elasticsearch/composable/component/user_agent.json
  usage-example/generated/elasticsearch/composable/template.json
  usage-example/generated/elasticsearch/legacy/template.json
Labels: needs_backport, 8.0.0

#1764 [8.1] Restructure `usage-examples` ES generated artifacts (#1762)
  CHANGELOG.next.md
  usage-example/README.md
  usage-example/generated/beats/fields.ecs.yml
  usage-example/generated/csv/fields.csv
  usage-example/generated/ecs/ecs_flat.yml
  usage-example/generated/ecs/ecs_nested.yml
  usage-example/generated/ecs/subset/web_logs/ecs_flat.yml
  usage-example/generated/ecs/subset/web_logs/ecs_nested.yml
  usage-example/generated/elasticsearch/6/template.json
  usage-example/generated/elasticsearch/composable/component/acme.json
  usage-example/generated/elasticsearch/composable/component/agent.json
  usage-example/generated/elasticsearch/composable/component/base.json
  usage-example/generated/elasticsearch/composable/component/client.json
  usage-example/generated/elasticsearch/composable/component/destination.json
  usage-example/generated/elasticsearch/composable/component/ecs.json
  usage-example/generated/elasticsearch/composable/component/event.json
  usage-example/generated/elasticsearch/composable/component/http.json
  usage-example/generated/elasticsearch/composable/component/network.json
  usage-example/generated/elasticsearch/composable/component/related.json
  usage-example/generated/elasticsearch/composable/component/server.json
  usage-example/generated/elasticsearch/composable/component/source.json
  usage-example/generated/elasticsearch/composable/component/url.json
  usage-example/generated/elasticsearch/composable/component/user.json
  usage-example/generated/elasticsearch/composable/component/user_agent.json
  usage-example/generated/elasticsearch/composable/template.json
  usage-example/generated/elasticsearch/legacy/template.json
Labels: backport

#1765 [8.0] Restructure `usage-examples` ES generated artifacts (#1762)
  CHANGELOG.next.md
  usage-example/README.md
  usage-example/generated/beats/fields.ecs.yml
  usage-example/generated/csv/fields.csv
  usage-example/generated/ecs/ecs_flat.yml
  usage-example/generated/ecs/ecs_nested.yml
  usage-example/generated/ecs/subset/web_logs/ecs_flat.yml
  usage-example/generated/ecs/subset/web_logs/ecs_nested.yml
  usage-example/generated/elasticsearch/6/template.json
  usage-example/generated/elasticsearch/composable/component/acme.json
  usage-example/generated/elasticsearch/composable/component/agent.json
  usage-example/generated/elasticsearch/composable/component/base.json
  usage-example/generated/elasticsearch/composable/component/client.json
  usage-example/generated/elasticsearch/composable/component/destination.json
  usage-example/generated/elasticsearch/composable/component/ecs.json
  usage-example/generated/elasticsearch/composable/component/event.json
  usage-example/generated/elasticsearch/composable/component/http.json
  usage-example/generated/elasticsearch/composable/component/network.json
  usage-example/generated/elasticsearch/composable/component/related.json
  usage-example/generated/elasticsearch/composable/component/server.json
  usage-example/generated/elasticsearch/composable/component/source.json
  usage-example/generated/elasticsearch/composable/component/url.json
  usage-example/generated/elasticsearch/composable/component/user.json
  usage-example/generated/elasticsearch/composable/component/user_agent.json
  usage-example/generated/elasticsearch/composable/template.json
  usage-example/generated/elasticsearch/legacy/template.json
Labels: backport

#1766 Cut 8.0.0 changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: needs_forward_port, 8.0.0

#1769 [8.2] Cut 8.0.0 changelog (#1766)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port

#1770 [8.1] Cut 8.0.0 changelog (#1766)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port

#1775 docs/using-ecs/guidelines/implementation: example json formatting fix
  docs/using-ecs/guidelines/implementation.asciidoc
Labels: needs_backport

#1776 [8.2] docs/using-ecs/guidelines/implementation: example json formatting fix (#1775)
  docs/using-ecs/guidelines/implementation.asciidoc
Labels: backport

#1778 [8.0] docs/using-ecs/guidelines/implementation: example json formatting fix (#1775)
  docs/using-ecs/guidelines/implementation.asciidoc
Labels: backport

#1782 Bump dependencies
  CHANGELOG.next.md
  scripts/requirements-dev.txt
  scripts/requirements.txt
Labels: needs_backport, 8.1.0

#1772 [DOCS] Add Kibana tutorial to ECS mapping docs
  docs/migrating/converting.asciidoc
  docs/migrating/images/kib-create-pipeline-from-csv-preview.png
  docs/migrating/images/kib-create-pipeline-from-csv.png
Labels: DOCS, 8.1.0, 8.2.0

#1785 [8.1] [DOCS] Add Kibana tutorial to ECS mapping docs (#1772)
  docs/migrating/converting.asciidoc
  docs/migrating/images/kib-create-pipeline-from-csv-preview.png
  docs/migrating/images/kib-create-pipeline-from-csv.png
Labels: backport, 8.1.0

#1783 [8.2] Bump dependencies (#1782)
  CHANGELOG.next.md
  scripts/requirements-dev.txt
  scripts/requirements.txt
Labels: backport

#1784 [8.1] Bump dependencies (#1782)
  CHANGELOG.next.md
  scripts/requirements-dev.txt
  scripts/requirements.txt
Labels: backport

#1788 [8.2] [DOCS] Add Kibana tutorial to ECS mapping docs (#1772)
  docs/migrating/converting.asciidoc
  docs/migrating/images/kib-create-pipeline-from-csv-preview.png
  docs/migrating/images/kib-create-pipeline-from-csv.png
Labels: backport

#1747 [RFC] Add container metric fields - Stage 2
  rfcs/text/0025-container-metric-fields.md
Labels: RFC

#1786 [8.1] Higher default compression for composable templates (#1712)
  CHANGELOG.next.md
Labels: backport

#1787 [8.2] Higher default compression for composable templates (#1712)
  CHANGELOG.next.md
Labels: backport

#1789 Implement proposed changes from RFC 0025 - `container.*` metric fields
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/schemas/container.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/container.json
  generated/elasticsearch/legacy/template.json
  schemas/container.yml
Labels: needs_backport, 8.2.0

#1704 [RFC] Introduce an `email` field set - stage 3
  rfcs/text/0010-email.md
  rfcs/text/0010/email.yml
  rfcs/text/0010/hash.yml
Labels: RFC

#1794 [RFC] RFC 0010 `email.*` field set - stage 3 changes
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  docs/fields/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/email.yml
  schemas/event.yml
Labels: needs_backport, 8.2.0

#1795 [8.2] [RFC] RFC 0010 `email.*` field set - stage 3 changes (#1794)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  docs/fields/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/email.yml
  schemas/event.yml
Labels: backport

#1800 [DOCS] Add release notes section
  CHANGELOG.next.md
  docs/index.asciidoc
  docs/release-notes/8.0.asciidoc
  docs/release-notes/8.1.asciidoc
  docs/release-notes/8.2.asciidoc
  docs/release-notes/index.asciidoc
  scripts/templates/index.j2
Labels: needs_backport, 8.2.0
