Repository elastic/ecs, pull requests merged in 2022-07, with the labels that each got.

#1984 [8.4] Adding service.node.roles (#1981)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/service.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/service.json
  generated/elasticsearch/legacy/template.json
  schemas/service.yml
Labels: backport

#1983 Cut 8.3.1 changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: needs_forward_port, 8.3.1

#1986 [main] changelog for 8.3.1 (#1983)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port

#1988 [8.4] 8.3.1 Release Notes
  docs/release-notes/8.3.1.asciidoc
  docs/release-notes/index.asciidoc
Labels: forward_port

#1989 [main] 8.3.1 Release Notes
  docs/release-notes/8.3.1.asciidoc
  docs/release-notes/index.asciidoc
Labels: forward_port

#1990 [8.3] 8.2.1 Release Notes
  docs/release-notes/8.2.1.asciidoc
  docs/release-notes/index.asciidoc
Labels: forward_port

#1991 [8.4] 8.2.1 Release Notes
  docs/release-notes/8.2.1.asciidoc
  docs/release-notes/index.asciidoc
Labels: forward_port

#1992 [main] 8.2.1 Release Notes
  docs/release-notes/8.2.1.asciidoc
  docs/release-notes/index.asciidoc
Labels: forward_port

#1744 [RFC 0031] Risk Fields- Stage 1
  rfcs/text/0031-risk-fields.md
Labels: RFC

#1928 GA threat.enrichments.indicator
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/as.yml
  schemas/file.yml
  schemas/geo.yml
  schemas/registry.yml
  schemas/threat.yml
  schemas/url.yml
  schemas/x509.yml
Labels: 8.5.0

#1953 [RFC] Stage 0 - Add new cloud fields
  rfcs/text/0033-new-cloud-fields.md
Labels: RFC

#1994 Adding `risk.*` fields as experimental
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/host.json
  experimental/generated/elasticsearch/composable/component/user.json
  experimental/generated/elasticsearch/legacy/template.json
  experimental/schemas/risk.yml
  experimental/schemas/subsets/experimental.yml
Labels: 8.5.0

#2000 Cutting 8.4 changelog for HFF
  CHANGELOG.next.md
Labels: needs_forward_port

#2005 [8.5] Cutting 8.4 HFF changelog
  CHANGELOG.next.md
Labels: forward_port

#2002 Adding 8.5 placeholder release notes
  docs/release-notes/8.5.asciidoc
  docs/release-notes/index.asciidoc
Labels: needs_forward_port

#2003 Cutting 8.5 changelog for SFF
  CHANGELOG.next.md
Labels: needs_forward_port

#2007 [main] adding 8.5 placeholder release notes (#2002)
  docs/release-notes/8.5.asciidoc
  docs/release-notes/index.asciidoc
Labels: forward_port

#2009 [main] 8.5 SFF changelog (#2003)
  CHANGELOG.next.md
Labels: forward_port

#2010 Fixing risk short fields
  CHANGELOG.next.md
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/schemas/risk.yml
Labels: needs_backport, 8.5.0

#2015 [8.5] Fixing risk short fields (#2010)
  CHANGELOG.next.md
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/schemas/risk.yml
Labels: backport

#2016 [8.5] Added `ios` and `android` as valid values for `os.type` (#1999)
  docs/fields/field-details.asciidoc
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/os.yml
Labels: backport

#2017 [8.5] rectify changelog 1999 (#2012)
  CHANGELOG.next.md
Labels: backport
