Repository elastic/ecs, pull requests merged in 2022-11, with the labels that each got.

#2082 [8.5] Linux event model GA
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/group.yml
  schemas/process.yml
  schemas/source.yml
  schemas/user.yml
Labels: needs_backport, 8.5.0

#2088 [8.6] [8.5] Linux event model GA (#2082)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/group.yml
  schemas/process.yml
  schemas/source.yml
  schemas/user.yml
Labels: backport

#2089 [8.5] [8.5] Linux event model GA (#2082)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/group.yml
  schemas/process.yml
  schemas/source.yml
  schemas/user.yml
Labels: backport

#2086 8.5 release notes
  docs/release-notes/8.5.asciidoc
Labels: needs_forward_port, 8.5.0

#2090 8.5 changelog (#2085)
  CHANGELOG.md
Labels: forward_port

#2091 8.5 changelog (#2085)
  CHANGELOG.md
Labels: forward_port

#2092 8.5 release notes (#2086)
  docs/release-notes/8.5.asciidoc
Labels: forward_port

#2093 8.5 release notes (#2086)
  docs/release-notes/8.5.asciidoc
Labels: forward_port

#2095 Fix typos in macho and pe schema files
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/macho.yml
  schemas/pe.yml
Labels: bug

#2094 Fix type of normalize for process.io.bytes_skipped
  CHANGELOG.next.md
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/process.yml
  scripts/tests/test_ecs_spec.py
Labels: bug, needs_backport, 8.5.1

#2099 Cut changelog for 8.5.1
  CHANGELOG.md
  CHANGELOG.next.md
Labels: needs_forward_port, 8.5.1

#2100 Add release notes for 8.5.1
  docs/release-notes/8.5.1.asciidoc
  docs/release-notes/index.asciidoc
Labels: needs_forward_port, 8.5.1

#2097 [8.6] Fix type of normalize for process.io.bytes_skipped (#2094)
  CHANGELOG.next.md
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/process.yml
  scripts/tests/test_ecs_spec.py
Labels: bug, backport, 8.6.0

#2102 Cut changelog for 8.5.1 (#2099)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port, 8.6.0

#2101 Cut changelog for 8.5.1 (#2099)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port, 8.5.1

#2104 Add release notes for 8.5.1 (#2100)
  docs/release-notes/8.5.1.asciidoc
  docs/release-notes/index.asciidoc
Labels: forward_port, 8.5.1

#2103 Add release notes for 8.5.1 (#2100)
  docs/release-notes/8.5.1.asciidoc
  docs/release-notes/index.asciidoc
Labels: forward_port, 8.5.1

#2105 Fixes invalid 'number' type on 4 process.io subfields.
  CHANGELOG.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/process.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/process.json
  generated/elasticsearch/legacy/template.json
  schemas/process.yml
Labels: bug, needs_backport, 8.5.2

#2107 [8.6] Fixes invalid 'number' type on 4 process.io subfields. (#2105)
  CHANGELOG.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/process.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/process.json
  generated/elasticsearch/legacy/template.json
  schemas/process.yml
Labels: backport

#2108 [8.5] Fixes invalid 'number' type on 4 process.io subfields. (#2105)
  CHANGELOG.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/process.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/process.json
  generated/elasticsearch/legacy/template.json
  schemas/process.yml
Labels: backport

#2110 Release notes for 8.5.2
  docs/release-notes/8.5.2.asciidoc
  docs/release-notes/index.asciidoc
Labels: needs_forward_port

#2111 [8.6] Release notes for 8.5.2
  docs/release-notes/8.5.2.asciidoc
  docs/release-notes/index.asciidoc
Labels: forward_port

#2112 [main] Release notes for 8.5.2
  docs/release-notes/8.5.2.asciidoc
  docs/release-notes/index.asciidoc
Labels: forward_port

#2116 [main] [elastic/ecs] Cutting 8.6 changelog for HFF (#2114)
  CHANGELOG.next.md
Labels: backport
