Repository elastic/ecs, pull requests merged in 2022-04, with the labels that each got.

#1872 [8.3] Add pattern attribute to `.mac` fields (#1871)
  CHANGELOG.next.md
  USAGE.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/client.yml
  schemas/destination.yml
  schemas/host.yml
  schemas/observer.yml
  schemas/server.yml
  schemas/source.yml
  scripts/schema/cleaner.py
  scripts/tests/unit/test_schema_cleaner.py
Labels: backport

#1875 Adding cluster.id to the orchestrator field set
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/orchestrator.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/orchestrator.json
  generated/elasticsearch/legacy/template.json
  schemas/orchestrator.yml
Labels: needs_backport, 8.3.0

#1876 [8.3] Adding cluster.id to the orchestrator field set (#1875)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/orchestrator.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/orchestrator.json
  generated/elasticsearch/legacy/template.json
  schemas/orchestrator.yml
Labels: backport

#1868 [RFC] Proposal to define ECS-compliance - Stage 1
  rfcs/text/0032-definition-of-ecs-compliance.md
Labels: RFC

#1879 Add `--force-docs` option
  CHANGELOG.next.md
  Makefile
  USAGE.md
  docs/fields/field-details.asciidoc
  docs/fields/fields.asciidoc
  docs/index.asciidoc
  scripts/generator.py
Labels: needs_backport, 8.2.0

#1878 Adding orchestrator.resource.id
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/orchestrator.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/orchestrator.json
  generated/elasticsearch/legacy/template.json
  schemas/orchestrator.yml
Labels: needs_backport, 8.3.0

#1880 [8.3] Add `--force-docs` option (#1879)
  CHANGELOG.next.md
  Makefile
  USAGE.md
  docs/fields/field-details.asciidoc
  scripts/generator.py
Labels: backport

#1881 [8.2] Add `--force-docs` option (#1879)
  CHANGELOG.next.md
  Makefile
  USAGE.md
  docs/fields/field-details.asciidoc
  scripts/generator.py
Labels: backport

#1882 [8.3] Adding orchestrator.resource.id (#1878)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/orchestrator.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/orchestrator.json
  generated/elasticsearch/legacy/template.json
  schemas/orchestrator.yml
Labels: backport

#1884 [DOCS] Include constraints for `process.env_vars` object field
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/process.yml
Labels: needs_backport, 8.2.0

#1887 [8.3] [DOCS] Include constraints for `process.env_vars` object field (#1884)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/process.yml
Labels: backport

#1888 [8.2] [DOCS] Include constraints for `process.env_vars` object field (#1884)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/process.yml
Labels: backport
