Repository elastic/ecs, pull requests merged in 2022-01, with the labels that each got.

#1710 docs: fix link to APM Overview
  docs/migrating/products-solutions.asciidoc
Labels: needs_backport, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, DOCS, 1.10.0, 8.0.0, 1.11.0, 1.12.0, 8.1.0

#1712 Higher default compression for composable templates
  CHANGELOG.next.md
  experimental/generated/elasticsearch/composable/template.json
  generated/elasticsearch/composable/template.json
  scripts/generators/es_template.py
Labels: 8.1.0

#1713 [8.1] docs: fix link to APM Overview (#1710)
  docs/migrating/products-solutions.asciidoc
Labels: backport

#1714 [8.0] docs: fix link to APM Overview (#1710)
  docs/migrating/products-solutions.asciidoc
Labels: backport

#1715 [1.12] docs: fix link to APM Overview (#1710)
  docs/products-solutions.asciidoc
Labels: backport

#1716 [1.11] docs: fix link to APM Overview (#1710)
  docs/products-solutions.asciidoc
Labels: backport

#1717 [1.10] docs: fix link to APM Overview (#1710)
  docs/products-solutions.asciidoc
Labels: backport

#1718 [1.9] docs: fix link to APM Overview (#1710)
  docs/products-solutions.asciidoc
Labels: backport

#1719 [1.8] docs: fix link to APM Overview (#1710)
  docs/products-solutions.asciidoc
Labels: backport

#1720 [1.7] docs: fix link to APM Overview (#1710)
  docs/products-solutions.asciidoc
Labels: backport

#1721 [1.6] docs: fix link to APM Overview (#1710)
  docs/products-solutions.asciidoc
Labels: backport

#1722 [1.5] docs: fix link to APM Overview (#1710)
  docs/products-solutions.asciidoc
Labels: backport

#1723 [1.4] docs: fix link to APM Overview (#1710)
  docs/products-solutions.asciidoc
Labels: backport

#1724 [1.3] docs: fix link to APM Overview (#1710)
  docs/products-solutions.asciidoc
Labels: backport

#1711 Beats: fix default_field setting for root fields
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  generated/beats/fields.ecs.yml
  scripts/generators/beats.py
  scripts/generators/ecs_helpers.py
  scripts/tests/unit/test_beats_generator.py
Labels: bug, needs_backport

#1726 [8.1] Beats: fix default_field setting for root fields (#1711)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  generated/beats/fields.ecs.yml
  scripts/generators/beats.py
  scripts/generators/ecs_helpers.py
  scripts/tests/unit/test_beats_generator.py
Labels: backport

#1727 [8.0] Beats: fix default_field setting for root fields (#1711)
  CHANGELOG.next.md
  experimental/generated/beats/fields.ecs.yml
  generated/beats/fields.ecs.yml
  scripts/generators/beats.py
  scripts/generators/ecs_helpers.py
  scripts/tests/unit/test_beats_generator.py
Labels: backport

#1728 Only generate documentation link in component template _meta for actual ecs fields
  CHANGELOG.next.md
  scripts/generators/es_template.py
Labels: 8.1.0

#1730 Cut 1.12.2 changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: 1.12.2

#1731 Fix typo for 1.12.2 changelog
  CHANGELOG.md
Labels: 1.12.2

#1733 [8.1] Cut 1.12.2 changelog (#1730)
  CHANGELOG.md
Labels: forward_port

#1734 [8.0] Cut 1.12.2 changelog (#1730)
  CHANGELOG.md
Labels: forward_port

#1732 [main] Cut 1.12.2 changelog (#1730)
  CHANGELOG.md
Labels: forward_port

#1739 broken link fix
  rfcs/PROCESS.md
Labels: bug

#1597 Introduce usage section for `threat.*` field set
  docs/fields/field-details.asciidoc
  docs/fields/usage/threat.asciidoc
Labels: DOCS, 8.1.0

#1740 [RFC] Add a reusable `risk` field set
  rfcs/text/0031-risk-fields.md
Labels: RFC

#1742 [8.1] Introduce usage section for `threat.*` field set (#1597)
  docs/fields/field-details.asciidoc
  docs/fields/usage/threat.asciidoc
Labels: backport

#1743 [8.0] Introduce usage section for `threat.*` field set (#1597)
  docs/fields/field-details.asciidoc
  docs/fields/usage/threat.asciidoc
Labels: backport

#1703 Add `Principles` docs section
  docs/using-ecs/design.asciidoc
  docs/using-ecs/guidelines.asciidoc
  docs/using-ecs/guidelines/conventions.asciidoc
  docs/using-ecs/guidelines/implementation.asciidoc
  docs/using-ecs/guidelines/mapping-network-events.asciidoc
  docs/using-ecs/index.asciidoc
Labels: needs_backport, DOCS, 8.1.0

#1745 [8.1] Add `Principles` docs section (#1703)
  docs/using-ecs/design.asciidoc
  docs/using-ecs/guidelines.asciidoc
  docs/using-ecs/guidelines/conventions.asciidoc
  docs/using-ecs/guidelines/implementation.asciidoc
  docs/using-ecs/guidelines/mapping-network-events.asciidoc
  docs/using-ecs/index.asciidoc
Labels: backport

#1746 [8.0] Add `Principles` docs section (#1703)
  docs/using-ecs/design.asciidoc
  docs/using-ecs/guidelines.asciidoc
  docs/using-ecs/guidelines/conventions.asciidoc
  docs/using-ecs/guidelines/implementation.asciidoc
  docs/using-ecs/guidelines/mapping-network-events.asciidoc
  docs/using-ecs/index.asciidoc
Labels: backport
