Repository elastic/ecs, pull requests merged in 2023-02, with the labels that each got.

#2147 Add the `api` value to `event.category`
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  docs/fields/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: needs_backport, 8.7.0

#2155 [8.7] Add the `api` value to `event.category` (#2147)
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  docs/fields/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: backport

#2156 Tlp patch
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/threat.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/threat.json
  generated/elasticsearch/legacy/template.json
  schemas/threat.yml
Labels: bug, needs_forward_port, 8.6.1

#2157 [main] Tlp patch #2156
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/threat.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/threat.json
  generated/elasticsearch/legacy/template.json
  schemas/threat.yml
Labels: 8.6.1

#2159 8.6.1 changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: needs_forward_port

#2160 Release notes for 8.6.1
  docs/release-notes/8.6.1.asciidoc
  docs/release-notes/index.asciidoc
Labels: needs_forward_port

#2154 Adding library category to the schema
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  docs/fields/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: needs_backport, 8.7.0

#2170 Fix typo
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/device.yml
Labels: 8.8.0

#2174 Permit `event.type: access` for `event.category: file` events
  CHANGELOG.next.md
  docs/fields/field-values.asciidoc
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: needs_backport, 8.8.0

#2084 Mapping parameters
  CHANGELOG.next.md
  scripts/generators/es_template.py
  scripts/tests/test_es_template.py
Labels: 8.8.0
