Repository elastic/ecs, pull requests merged in 2023-03, with the labels that each got.

#2184 [8.7.0 release] Move 8.7.0 entries from CHANGELOG.next.md to CHANGELOG.md
  CHANGELOG.md
  CHANGELOG.next.md
Labels: needs_forward_port

#2187 [8.7 forward port] Move 8.7.0 entries from CHANGELOG.next.md to CHANGELOG.md (#2184)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port

#2178 [RFC] Extend event.kind allowed values with asset
  rfcs/text/0038-event-kind-asset.md
  rfcs/text/0038/event.yml
Labels: RFC
