Repository elastic/ecs, pull requests merged in 2023-04, with the labels that each got.

#2198 8.8 FF changelog updates
  CHANGELOG.next.md
Labels: needs_forward_port

#2200 [main] Changelog for 8.8 ff (#2198)
  CHANGELOG.next.md
Labels: forward_port

#2181 Orchestrator additions for features coming in 8.8
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  experimental/generated/elasticsearch/composable/component/orchestrator.json
  experimental/generated/elasticsearch/legacy/template.json
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  generated/elasticsearch/composable/component/orchestrator.json
  generated/elasticsearch/legacy/template.json
  schemas/orchestrator.yml
Labels: needs_backport, 8.8.0
