Repository elastic/ecs, pull requests merged in 2023-09, with the labels that each got.

#2266 [8.10] Bump gitpython from 3.1.32 to 3.1.34 in /scripts (#2264)
  CHANGELOG.next.md
  scripts/requirements.txt
Labels: backport

#2268 [8.10] Bump gitpython from 3.1.34 to 3.1.35 in /scripts (#2265)
  CHANGELOG.next.md
  scripts/requirements.txt
Labels: backport

#2271 Finalize 8.10 changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: needs_forward_port

#2272 [main] Finalize 8.10 changelog (#2271)
  CHANGELOG.md
  CHANGELOG.next.md
Labels: forward_port

#2273 Release notes for 8.10
  docs/release-notes/8.10.asciidoc
  docs/release-notes/index.asciidoc
Labels: needs_forward_port

#2274 [main] Release notes for ECS 8.10 (#2273)
  docs/release-notes/8.10.asciidoc
  docs/release-notes/index.asciidoc
Labels: forward_port
