Repository elastic/ecs, pull requests merged in 2023-11, with the labels that each got.

#2300 Upgrading pyyaml dependency to fix build failures
  scripts/requirements.txt
  scripts/schema/cleaner.py
Labels: needs_backport

#2301 [8.11] Upgrading pyyaml dependency to fix build failures (#2300)
  scripts/requirements.txt
  scripts/schema/cleaner.py
Labels: backport

#2296 Finalize 8.11 changelog
  CHANGELOG.md
Labels: forward_port

#2295 Finalize 8.11 changelog
  CHANGELOG.md
  CHANGELOG.next.md
Labels: needs_forward_port

#2297 Release notes for 8.11
  docs/release-notes/8.11.asciidoc
  docs/release-notes/index.asciidoc
Labels: needs_forward_port

#2298 Release notes for 8.11
  docs/release-notes/8.11.asciidoc
  docs/release-notes/index.asciidoc
Labels: forward_port
