Repository elastic/ecs, pull requests merged in 2023-10, with the labels that each got.

#2281 Remove `expected_values` from *.indicator.name field defs
  CHANGELOG.next.md
  docs/fields/field-details.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/threat.yml
Labels: bug, 8.11

#2284 8.11 FF changelog updates
  CHANGELOG.next.md
Labels: needs_forward_port, Team: ECS

#2285 8.11 FF changelog updates (#2284)
  CHANGELOG.next.md
Labels: Team: ECS

#2286 Add 8.11 to backport tool
  .backportrc.json
Labels: Team: ECS

#2293 [8.11] Bump gitpython from 3.1.35 to 3.1.37 in /scripts (#2292)
  scripts/requirements.txt
Labels: backport
