Repository elastic/ecs, pull requests merged in 2023-06, with the labels that each got.

#2201 [RFC] Stge 0 - New fieldset for volume device
  rfcs/text/0040-volume-device.md
Labels: RFC

#2222 8.9 FF changelog updates
  CHANGELOG.next.md
Labels: needs_forward_port

#2224 [main] 8.9 changelog forwardport
  CHANGELOG.next.md
Labels: forward_port

#2226 [Event] Clean up Event fields
  docs/fields/field-details.asciidoc
  docs/fields/field-values.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: needs_backport

#2227 [8.9] Clean up Event fields (#2226)
  docs/fields/field-details.asciidoc
  docs/fields/field-values.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: backport

#2228 [8.8] Clean up Event fields (#2226)
  docs/fields/field-details.asciidoc
  docs/fields/field-values.asciidoc
  experimental/generated/beats/fields.ecs.yml
  experimental/generated/csv/fields.csv
  experimental/generated/ecs/ecs_flat.yml
  experimental/generated/ecs/ecs_nested.yml
  generated/beats/fields.ecs.yml
  generated/csv/fields.csv
  generated/ecs/ecs_flat.yml
  generated/ecs/ecs_nested.yml
  schemas/event.yml
Labels: backport
